"""What a model said, what checked it, and whether it survived.

A proposal is inert until something deterministic agrees with it. These types
exist so that a caller cannot accidentally use an unchecked one: the value is
only reachable through :meth:`Proposal.confirmed_value`, which raises unless a
check has recorded a verdict of ``confirmed``.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional


class Verdict(str, Enum):
    """What the deterministic check made of a proposal."""

    #: A check ran and the artefact agrees with what was proposed.
    CONFIRMED = "confirmed"
    #: A check ran and the artefact disagrees. The proposal is discarded.
    CONTRADICTED = "contradicted"
    #: No check could run. The proposal is recorded and must not be used.
    UNVERIFIED = "unverified"


class ProposalNotConfirmed(RuntimeError):
    """Raised when an unchecked proposal is asked for its value."""


@dataclass
class Proposal:
    """One suggestion from a model, and the evidence for or against it."""

    subject: str
    proposed: Any
    model: str
    verdict: Verdict = Verdict.UNVERIFIED
    checked_by: str = ""
    evidence: str = ""
    alternatives: tuple[str, ...] = ()
    prompt_sha256: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def confirm(self, *, checked_by: str, evidence: str) -> "Proposal":
        self.verdict = Verdict.CONFIRMED
        self.checked_by = checked_by
        self.evidence = evidence
        return self

    def contradict(self, *, checked_by: str, evidence: str) -> "Proposal":
        self.verdict = Verdict.CONTRADICTED
        self.checked_by = checked_by
        self.evidence = evidence
        return self

    def confirmed_value(self) -> Any:
        """The proposal, but only once something has agreed with it."""
        if self.verdict is not Verdict.CONFIRMED:
            raise ProposalNotConfirmed(
                f"{self.subject}: a proposal is not usable until a "
                f"deterministic check confirms it (verdict is "
                f"{self.verdict.value}"
                + (f"; {self.evidence}" if self.evidence else "") + ")")
        return self.proposed

    def as_dict(self) -> dict[str, Any]:
        return {
            "subject": self.subject,
            "proposed": self.proposed,
            "model": self.model,
            "verdict": self.verdict.value,
            "checked_by": self.checked_by,
            "evidence": self.evidence,
            "alternatives": list(self.alternatives),
            "prompt_sha256": self.prompt_sha256,
            "note": ("A model selected among artefacts that already existed. "
                     "No value here was generated by it: the numbers are read "
                     "from the file the selection names, by a parser."),
            **({"metadata": self.metadata} if self.metadata else {}),
        }
