"""The paper-ready summary must be generated, and must keep outcomes distinct."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SUMMARY = REPO_ROOT / "paper_results" / "PAPER_READY_SUMMARY.md"
SWEEP = (REPO_ROOT / "paper_results" / "parameter_sensitivity"
         / "parameter_sensitivity_round.json")
CORPUS = REPO_ROOT / "paper_results" / "corpus" / "corpus_round.json"


@pytest.fixture(scope="module")
def text() -> str:
    if not SUMMARY.is_file():
        pytest.skip("the paper summary has not been generated")
    return SUMMARY.read_text(encoding="utf-8")


def test_declares_itself_generated(text):
    assert "GENERATED by tools/build_paper_summary.py" in text


def test_every_sentence_cites_an_artefact_and_commit(text):
    quotes = [line for line in text.splitlines() if line.startswith("> ")]
    sources = [line for line in text.splitlines() if line.startswith("Source: ")]
    assert quotes and len(quotes) == len(sources)
    for line in sources:
        assert re.search(r"Source: `[^`]+`\.", line), line
    # The commit is stated once, in the header.
    assert re.search(r"produced at commit `[0-9a-f]{7,40}`", text)


def test_numbers_match_the_executed_sweep(text):
    funnel = json.loads(SWEEP.read_text(encoding="utf-8"))["funnel"]
    assert str(funnel["comparison_rows_agreeing"]) in text
    assert str(funnel["comparison_rows_total"]) in text
    assert (f"{funnel['parameter_directions_verified']} of "
            f"{funnel['parameter_directions_declared']}") in text


def test_corpus_numbers_match_the_executed_round(text):
    if not CORPUS.is_file():
        pytest.skip("no corpus round")
    funnel = json.loads(CORPUS.read_text(encoding="utf-8"))["funnel"]
    verified = funnel["reached_derivatives_verified"]
    assert f"{verified} verified numerically" in text


def test_outcomes_are_not_conflated(text):
    """Compiled, executed, parity-verified and derivative-verified stay distinct."""
    assert "*compiled* is not *executed*" in text
    assert "Reference unresolved" in text or "reference-unresolved" in text
    assert "missing external data, not a transformation failure" in text


def test_archived_abaqus_run_is_not_given_a_version_it_never_recorded(text):
    """The archive records job, host and compiler -- not the Abaqus release."""
    if "Slurm job" not in text:
        pytest.skip("no archived Abaqus evidence")
    assert "does not record the Abaqus version" in text
    assert not re.search(r"Abaqus 20\d\d", text), \
        "a specific Abaqus release was asserted for a run that did not record one"


def test_probe_material_caveat_is_present(text):
    if "Slurm job" not in text:
        pytest.skip("no archived Abaqus evidence")
    assert "probe property vector" in text


@pytest.mark.slow
def test_regenerates_identically_except_for_its_timestamp(tmp_path):
    out = tmp_path / "summary.md"
    subprocess.run(
        [sys.executable, str(REPO_ROOT / "tools" / "build_paper_summary.py"),
         "--out", str(out)],
        cwd=REPO_ROOT, check=True, capture_output=True)

    def strip(value: str) -> str:
        """Remove everything that legitimately varies between regenerations.

        The commit appears twice in the header. A clean clone regenerates at a
        different HEAD, so leaving either in place makes the document differ
        from itself for a reason that is not a change in any measurement.
        """
        value = re.sub(r"Generated \S+ from commit `[0-9a-f]+`\.", "", value)
        return re.sub(r"produced at commit `[0-9a-f]+`", "", value)

    assert strip(out.read_text(encoding="utf-8")) == strip(
        SUMMARY.read_text(encoding="utf-8"))
