"""The reconciliation must report evidence, and must not be edited by hand."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
DOC = REPO_ROOT / "docs" / "PUBLICATION_RESULTS_RECONCILIATION.md"
CLAIMS = REPO_ROOT / "docs" / "manuscript_claims.json"
ROUND = (REPO_ROOT / "paper_results" / "parameter_sensitivity"
         / "parameter_sensitivity_round.json")


def test_document_declares_itself_generated():
    assert "GENERATED by tools/build_publication_reconciliation.py" in DOC.read_text()


def test_manuscript_values_are_never_read_by_code():
    """Transcribed claims are context. Nothing may compare against them.

    A tolerance or expected value taken from the manuscript would make the paper
    its own reference, which is exactly what this project forbids.
    """
    claims = json.loads(CLAIMS.read_text(encoding="utf-8"))
    readers = subprocess.run(
        ["git", "grep", "-l", "manuscript_claims", "--", "src", "tools", "tests"],
        cwd=REPO_ROOT, capture_output=True, text=True)
    allowed = {"tools/build_publication_reconciliation.py",
               "tests/test_publication_reconciliation.py"}
    found = {line.strip() for line in readers.stdout.splitlines() if line.strip()}
    assert found <= allowed, f"manuscript claims are read by {found - allowed}"
    assert claims["source_document"]["sha256"]


def test_table6_funnel_matches_the_executed_round():
    payload = json.loads(ROUND.read_text(encoding="utf-8"))
    funnel = payload["funnel"]
    text = DOC.read_text(encoding="utf-8")
    row = next(line for line in text.splitlines() if line.startswith("| **Table 6**"))
    cells = [c.strip() for c in row.split("|")[2:-1]]
    # required, attempted, transformed, compiled, executed, primal_parity,
    # reference_resolved, verified, ...
    assert cells[0] == str(funnel["parameter_directions_declared"])
    assert cells[1] == str(funnel["attempted"])
    assert cells[7] == str(funnel["parameter_directions_verified"])


def test_blank_cells_are_documented_as_not_applicable():
    assert "Blank cells mean the stage does not apply" in DOC.read_text()


@pytest.mark.slow
def test_regenerates_identically_except_for_its_timestamp(tmp_path):
    out = tmp_path / "regenerated.md"
    subprocess.run(
        [sys.executable, str(REPO_ROOT / "tools" / "build_publication_reconciliation.py"),
         "--out", str(out)],
        cwd=REPO_ROOT, check=True, capture_output=True)

    def strip(text: str) -> str:
        return re.sub(r"Generated \S+ from commit `[0-9a-f]+`\.", "", text)

    assert strip(out.read_text(encoding="utf-8")) == strip(DOC.read_text(encoding="utf-8"))
