      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
C     Isotropic linear elasticity in Lame parameters: lambda=PROPS(1), mu=PROPS(2).
C     Self-contained, small strain, ntens 6.
      INCLUDE 'ABA_PARAM.INC'
      CHARACTER*80 CMNAME
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)
      PARAMETER (ZERO=0.D0, ONE=1.D0, TWO=2.D0)
      INTEGER K1,K2
      ELAM = PROPS(1)
      EG   = PROPS(2)
      DO K1 = 1,NTENS
        DO K2 = 1,NTENS
          DDSDDE(K1,K2) = ZERO
        END DO
      END DO
      DO K1 = 1,3
        DO K2 = 1,3
          DDSDDE(K2,K1) = ELAM
        END DO
        DDSDDE(K1,K1) = ELAM + TWO*EG
      END DO
      DDSDDE(4,4) = EG
      DDSDDE(5,5) = EG
      DDSDDE(6,6) = EG
      DO K1 = 1,NTENS
        DSTR = ZERO
        DO K2 = 1,NTENS
          DSTR = DSTR + DDSDDE(K1,K2)*DSTRAN(K2)
        END DO
        STRESS(K1) = STRESS(K1) + DSTR
      END DO
      RETURN
      END
