"""Complex numbers over the OTI algebra: the ``oti_complex`` Fortran module.

The OTI number generated by :mod:`umat_oti.oti.module_generator` is a
truncated multivariate Taylor polynomial with REAL coefficients. A source that
declares ``DOUBLE COMPLEX`` on the stress path needs a value that is complex
AND carries derivatives. This module supplies one:

    TYPE Z<T>                 ! e.g. ZONUMM6N1 over ONUMM6N1
      TYPE(<T>) :: RE, IM     ! z = RE + i*IM, each part a real OTI number
    END TYPE

The complex unit ``i`` and the OTI imaginary directions ``e_k`` are
independent, commuting units: the algebra is C (x) OTI, never a mixture. So a
complex step an author writes in the source (``x + i*h``, then
``AIMAG(f)/h``) stays an ordinary complex number here; its ``i`` is never
mistaken for an OTI direction, and the OTI parts of every quantity remain
derivatives with respect to the seeded inputs.

Derivative semantics. Every operation is implemented as the real-analytic map
``(re, im) -> (re', im')`` evaluated in real OTI arithmetic. For a
holomorphic f this gives exactly the truncated Taylor expansion of f in the
perturbation ``delta = d(re) + i d(im)``, i.e. ``f'(z) * delta`` at first
order. For the non-holomorphic but real-differentiable maps REAL/DBLE, AIMAG,
CONJG and ABS it gives the derivative of the real map, so derivatives of the
real and imaginary parts propagate as real OTI numbers.

Non-smooth points and branch cuts (documented, not hidden):

* ``ABS(z)`` at ``z = 0`` is a cone point (not differentiable). The value 0 is
  returned with zero derivative -- the same convention the real OTI ``ABS``
  uses at 0.
* ``SQRT(z)`` and ``LOG(z)`` (and ``z**w`` for non-integer w, defined as
  ``EXP(w*LOG(z))``) use the principal branch, cut along the negative real
  axis, matching the Fortran intrinsics including the sign of a zero imaginary
  part (``SQRT(-4 - 0i) = -2i``). On the cut the derivative returned is the
  one-sided derivative from the side the imaginary part's sign selects; a
  perturbation that crosses the cut sees a discontinuous function, and a
  finite difference of the original will not agree there. ``SQRT(0)``,
  ``LOG(0)``, ``0**w`` are not differentiable: value as the intrinsic,
  derivative zero (SQRT/POW) or the intrinsic's -inf (LOG).
* ``ATAN2(y, x)`` over the real OTI type (needed for ARG and by the corpus
  helpers) has derivative ``(x dy - y dx)/(x^2 + y^2)`` on both sides of its
  cut ``x < 0, y = 0``; its value jumps by 2*pi there, following the sign of y
  (``ATAN2(-0, -1) = -pi``). At ``x = y = 0`` the derivative is zero.

Comparisons (``==``, ``/=``) look at values only, like the real OTI ones.
Assigning a complex OTI to a plain ``COMPLEX`` is deliberately NOT provided:
it would drop the derivative silently, so it stays a compile error.
"""
from __future__ import annotations

from pathlib import Path

#: The Fortran module name; one per transform output directory.
COMPLEX_MODULE_NAME = "oti_complex"
COMPLEX_MODULE_FILE = f"{COMPLEX_MODULE_NAME}.f90"

#: Every generic name the module adds or extends. A source that uses one of
#: these as a variable name collides with the USE; complex_support checks it.
EXPORTED_GENERICS = (
    "DCMPLX", "CMPLX", "DBLE", "REAL", "AIMAG", "CONJG", "ABS", "SQRT", "LOG",
    "EXP", "SIN", "COS", "TAN", "SINH", "COSH", "ATAN2", "OTI_CVALUE",
)


def complex_type_name(type_name: str) -> str:
    """``ONUMM6N1`` -> ``ZONUMM6N1``."""
    return f"Z{type_name.upper()}"


_TEMPLATE = r"""
! Generated by umat_oti.oti.complex_oti -- complex numbers over the OTI algebra.
! @Z@ = RE + i*IM with RE, IM of TYPE(@T@). The complex unit i and the OTI
! directions are independent commuting units (C x OTI). See complex_oti.py for
! the derivative semantics, branch cuts and non-smooth points.
MODULE oti_complex
  USE master_parameters, ONLY: DP
  USE @M@
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: @Z@
  PUBLIC :: OPERATOR(+), OPERATOR(-), OPERATOR(*), OPERATOR(/), OPERATOR(**)
  PUBLIC :: OPERATOR(==), OPERATOR(/=), ASSIGNMENT(=)
  PUBLIC :: DCMPLX, CMPLX, DBLE, REAL, AIMAG, CONJG, ABS, SQRT, LOG, EXP
  PUBLIC :: SIN, COS, TAN, SINH, COSH, ATAN2, OTI_CVALUE

  TYPE @Z@
    TYPE(@T@) :: RE
    TYPE(@T@) :: IM
  END TYPE @Z@

  REAL(DP), PARAMETER :: ZPI = 3.14159265358979323846264338327950288_DP

  INTERFACE OPERATOR(+)
    MODULE PROCEDURE @Z@_ADD_ZZ, @Z@_ADD_ZT, @Z@_ADD_TZ, @Z@_ADD_ZR, @Z@_ADD_RZ, &
                     @Z@_ADD_ZC, @Z@_ADD_CZ, @Z@_ADD_ZI, @Z@_ADD_IZ, @Z@_ADD_TC, &
                     @Z@_ADD_CT, @Z@_UPLUS
  END INTERFACE
  INTERFACE OPERATOR(-)
    MODULE PROCEDURE @Z@_SUB_ZZ, @Z@_SUB_ZT, @Z@_SUB_TZ, @Z@_SUB_ZR, @Z@_SUB_RZ, &
                     @Z@_SUB_ZC, @Z@_SUB_CZ, @Z@_SUB_ZI, @Z@_SUB_IZ, @Z@_SUB_TC, &
                     @Z@_SUB_CT, @Z@_NEG
  END INTERFACE
  INTERFACE OPERATOR(*)
    MODULE PROCEDURE @Z@_MUL_ZZ, @Z@_MUL_ZT, @Z@_MUL_TZ, @Z@_MUL_ZR, @Z@_MUL_RZ, &
                     @Z@_MUL_ZC, @Z@_MUL_CZ, @Z@_MUL_ZI, @Z@_MUL_IZ, @Z@_MUL_TC, &
                     @Z@_MUL_CT
  END INTERFACE
  INTERFACE OPERATOR(/)
    MODULE PROCEDURE @Z@_DIV_ZZ, @Z@_DIV_ZT, @Z@_DIV_TZ, @Z@_DIV_ZR, @Z@_DIV_RZ, &
                     @Z@_DIV_ZC, @Z@_DIV_CZ, @Z@_DIV_ZI, @Z@_DIV_IZ, @Z@_DIV_TC, &
                     @Z@_DIV_CT
  END INTERFACE
  INTERFACE OPERATOR(**)
    MODULE PROCEDURE @Z@_POW_ZI, @Z@_POW_ZR, @Z@_POW_ZT, @Z@_POW_ZZ, @Z@_POW_ZC, &
                     @Z@_POW_RZ, @Z@_POW_TZ, @Z@_POW_CZ
  END INTERFACE
  INTERFACE OPERATOR(==)
    MODULE PROCEDURE @Z@_EQ_ZZ, @Z@_EQ_ZC, @Z@_EQ_CZ, @Z@_EQ_ZR, @Z@_EQ_RZ
  END INTERFACE
  INTERFACE OPERATOR(/=)
    MODULE PROCEDURE @Z@_NE_ZZ, @Z@_NE_ZC, @Z@_NE_CZ, @Z@_NE_ZR, @Z@_NE_RZ
  END INTERFACE
  INTERFACE ASSIGNMENT(=)
    MODULE PROCEDURE @Z@_ASSIGN_C, @Z@_ASSIGN_R, @Z@_ASSIGN_I, @Z@_ASSIGN_T, &
                     @Z@_ASSIGN_TO_T
  END INTERFACE
  INTERFACE DCMPLX
    MODULE PROCEDURE @Z@_FROM_TT, @Z@_FROM_TR, @Z@_FROM_RT, @Z@_FROM_TI, &
                     @Z@_FROM_IT, @Z@_FROM_T, @Z@_FROM_Z
  END INTERFACE
  INTERFACE CMPLX
    MODULE PROCEDURE @Z@_FROM_TT, @Z@_FROM_TR, @Z@_FROM_RT, @Z@_FROM_TI, &
                     @Z@_FROM_IT, @Z@_FROM_T, @Z@_FROM_Z, @Z@_FROM_TT_K, &
                     @Z@_FROM_TR_K, @Z@_FROM_RT_K, @Z@_FROM_Z_K
  END INTERFACE
  INTERFACE DBLE
    MODULE PROCEDURE @Z@_DBLE_Z, @Z@_DBLE_T
  END INTERFACE
  INTERFACE REAL
    MODULE PROCEDURE @Z@_REAL_Z, @Z@_REAL_ZK
  END INTERFACE
  INTERFACE AIMAG
    MODULE PROCEDURE @Z@_AIMAG
  END INTERFACE
  INTERFACE CONJG
    MODULE PROCEDURE @Z@_CONJG
  END INTERFACE
  INTERFACE ABS
    MODULE PROCEDURE @Z@_ABS
  END INTERFACE
  INTERFACE SQRT
    MODULE PROCEDURE @Z@_SQRT
  END INTERFACE
  INTERFACE LOG
    MODULE PROCEDURE @Z@_LOG
  END INTERFACE
  INTERFACE EXP
    MODULE PROCEDURE @Z@_EXP
  END INTERFACE
  INTERFACE SIN
    MODULE PROCEDURE @Z@_SIN
  END INTERFACE
  INTERFACE COS
    MODULE PROCEDURE @Z@_COS
  END INTERFACE
  INTERFACE TAN
    MODULE PROCEDURE @Z@_TAN
  END INTERFACE
  INTERFACE SINH
    MODULE PROCEDURE @Z@_SINH
  END INTERFACE
  INTERFACE COSH
    MODULE PROCEDURE @Z@_COSH
  END INTERFACE
  INTERFACE ATAN2
    MODULE PROCEDURE @T@_ATAN2_TT, @T@_ATAN2_TR, @T@_ATAN2_RT
  END INTERFACE
  INTERFACE OTI_CVALUE
    MODULE PROCEDURE @Z@_CVALUE
  END INTERFACE

CONTAINS

  ! ---------------------------------------------------------------- helpers
  ELEMENTAL FUNCTION @Z@_TR(X) RESULT(RES)
    REAL(DP), INTENT(IN) :: X
    TYPE(@T@) :: RES
    RES = X
  END FUNCTION @Z@_TR

  ELEMENTAL FUNCTION @Z@_OF_T(X) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: X
    TYPE(@Z@) :: RES
    RES%RE = X
    RES%IM = 0.0_DP
  END FUNCTION @Z@_OF_T

  ELEMENTAL FUNCTION @Z@_OF_C(X) RESULT(RES)
    COMPLEX(DP), INTENT(IN) :: X
    TYPE(@Z@) :: RES
    RES%RE = REAL(X, DP)
    RES%IM = AIMAG(X)
  END FUNCTION @Z@_OF_C

  ELEMENTAL FUNCTION @Z@_OF_R(X) RESULT(RES)
    REAL(DP), INTENT(IN) :: X
    TYPE(@Z@) :: RES
    RES%RE = X
    RES%IM = 0.0_DP
  END FUNCTION @Z@_OF_R

  ELEMENTAL LOGICAL FUNCTION @Z@_IS_ZERO(Z)
    TYPE(@Z@), INTENT(IN) :: Z
    @Z@_IS_ZERO = (REAL(Z%RE) == 0.0_DP) .AND. (REAL(Z%IM) == 0.0_DP)
  END FUNCTION @Z@_IS_ZERO

  ! ------------------------------------------------------------ assignment
  ELEMENTAL SUBROUTINE @Z@_ASSIGN_C(RES, X)
    TYPE(@Z@), INTENT(OUT) :: RES
    COMPLEX(DP), INTENT(IN) :: X
    RES%RE = REAL(X, DP)
    RES%IM = AIMAG(X)
  END SUBROUTINE @Z@_ASSIGN_C

  ELEMENTAL SUBROUTINE @Z@_ASSIGN_R(RES, X)
    TYPE(@Z@), INTENT(OUT) :: RES
    REAL(DP), INTENT(IN) :: X
    RES%RE = X
    RES%IM = 0.0_DP
  END SUBROUTINE @Z@_ASSIGN_R

  ELEMENTAL SUBROUTINE @Z@_ASSIGN_I(RES, X)
    TYPE(@Z@), INTENT(OUT) :: RES
    INTEGER, INTENT(IN) :: X
    RES%RE = REAL(X, DP)
    RES%IM = 0.0_DP
  END SUBROUTINE @Z@_ASSIGN_I

  ELEMENTAL SUBROUTINE @Z@_ASSIGN_T(RES, X)
    TYPE(@Z@), INTENT(OUT) :: RES
    TYPE(@T@), INTENT(IN) :: X
    RES%RE = X
    RES%IM = 0.0_DP
  END SUBROUTINE @Z@_ASSIGN_T

  ! Fortran assigns a complex to a real by taking its real part; the
  ! derivative of the real part is kept.
  ELEMENTAL SUBROUTINE @Z@_ASSIGN_TO_T(RES, X)
    TYPE(@T@), INTENT(OUT) :: RES
    TYPE(@Z@), INTENT(IN) :: X
    RES = X%RE
  END SUBROUTINE @Z@_ASSIGN_TO_T

  ! ------------------------------------------------- arithmetic
  ! Complex (x) complex. Mixed operands are PROMOTED first -- a real r
  ! becomes (r, +0) -- and then the complex operation is done, which is what
  ! the Fortran standard prescribes and what gfortran does, including the sign
  ! of a zero imaginary part (it decides the side of SQRT's and LOG's cut).
  ! The extra products with that zero carry no derivative.
  ELEMENTAL FUNCTION @Z@_ADD_ZZ(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A, B
    TYPE(@Z@) :: RES
    RES%RE = A%RE + B%RE
    RES%IM = A%IM + B%IM
  END FUNCTION @Z@_ADD_ZZ

  ELEMENTAL FUNCTION @Z@_SUB_ZZ(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A, B
    TYPE(@Z@) :: RES
    RES%RE = A%RE - B%RE
    RES%IM = A%IM - B%IM
  END FUNCTION @Z@_SUB_ZZ

  ELEMENTAL FUNCTION @Z@_MUL_ZZ(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A, B
    TYPE(@Z@) :: RES
    RES%RE = A%RE*B%RE - A%IM*B%IM
    RES%IM = A%RE*B%IM + A%IM*B%RE
  END FUNCTION @Z@_MUL_ZZ

  ! Smith's algorithm, branch chosen on the VALUES so the arithmetic matches a
  ! compiler's complex division closely; each branch is an exact algebraic
  ! identity, so the OTI parts are the exact derivative of the quotient.
  ELEMENTAL FUNCTION @Z@_DIV_ZZ(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A, B
    TYPE(@Z@) :: RES
    TYPE(@T@) :: R, DEN
    IF (ABS(REAL(B%RE)) >= ABS(REAL(B%IM))) THEN
      R = B%IM / B%RE
      DEN = B%RE + B%IM*R
      RES%RE = (A%RE + A%IM*R) / DEN
      RES%IM = (A%IM - A%RE*R) / DEN
    ELSE
      R = B%RE / B%IM
      DEN = B%RE*R + B%IM
      RES%RE = (A%RE*R + A%IM) / DEN
      RES%IM = (A%IM*R - A%RE) / DEN
    END IF
  END FUNCTION @Z@_DIV_ZZ

  ELEMENTAL FUNCTION @Z@_UPLUS(A) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    TYPE(@Z@) :: RES
    RES = A
  END FUNCTION @Z@_UPLUS

  ELEMENTAL FUNCTION @Z@_NEG(A) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    TYPE(@Z@) :: RES
    RES%RE = -A%RE
    RES%IM = -A%IM
  END FUNCTION @Z@_NEG

  ELEMENTAL FUNCTION @Z@_OF_I(X) RESULT(RES)
    INTEGER, INTENT(IN) :: X
    TYPE(@Z@) :: RES
    RES%RE = REAL(X, DP)
    RES%IM = 0.0_DP
  END FUNCTION @Z@_OF_I

  ELEMENTAL FUNCTION @Z@_ADD_ZT(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    TYPE(@T@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_ADD_ZZ(A, @Z@_OF_T(B))
  END FUNCTION @Z@_ADD_ZT

  ELEMENTAL FUNCTION @Z@_ADD_TZ(A, B) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_ADD_ZZ(@Z@_OF_T(A), B)
  END FUNCTION @Z@_ADD_TZ

  ELEMENTAL FUNCTION @Z@_ADD_ZR(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    REAL(DP), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_ADD_ZZ(A, @Z@_OF_R(B))
  END FUNCTION @Z@_ADD_ZR

  ELEMENTAL FUNCTION @Z@_ADD_RZ(A, B) RESULT(RES)
    REAL(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_ADD_ZZ(@Z@_OF_R(A), B)
  END FUNCTION @Z@_ADD_RZ

  ELEMENTAL FUNCTION @Z@_ADD_ZC(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    COMPLEX(DP), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_ADD_ZZ(A, @Z@_OF_C(B))
  END FUNCTION @Z@_ADD_ZC

  ELEMENTAL FUNCTION @Z@_ADD_CZ(A, B) RESULT(RES)
    COMPLEX(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_ADD_ZZ(@Z@_OF_C(A), B)
  END FUNCTION @Z@_ADD_CZ

  ELEMENTAL FUNCTION @Z@_ADD_ZI(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_ADD_ZZ(A, @Z@_OF_I(B))
  END FUNCTION @Z@_ADD_ZI

  ELEMENTAL FUNCTION @Z@_ADD_IZ(A, B) RESULT(RES)
    INTEGER, INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_ADD_ZZ(@Z@_OF_I(A), B)
  END FUNCTION @Z@_ADD_IZ

  ELEMENTAL FUNCTION @Z@_ADD_TC(A, B) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: A
    COMPLEX(DP), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_ADD_ZZ(@Z@_OF_T(A), @Z@_OF_C(B))
  END FUNCTION @Z@_ADD_TC

  ELEMENTAL FUNCTION @Z@_ADD_CT(A, B) RESULT(RES)
    COMPLEX(DP), INTENT(IN) :: A
    TYPE(@T@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_ADD_ZZ(@Z@_OF_C(A), @Z@_OF_T(B))
  END FUNCTION @Z@_ADD_CT

  ELEMENTAL FUNCTION @Z@_SUB_ZT(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    TYPE(@T@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_SUB_ZZ(A, @Z@_OF_T(B))
  END FUNCTION @Z@_SUB_ZT

  ELEMENTAL FUNCTION @Z@_SUB_TZ(A, B) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_SUB_ZZ(@Z@_OF_T(A), B)
  END FUNCTION @Z@_SUB_TZ

  ELEMENTAL FUNCTION @Z@_SUB_ZR(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    REAL(DP), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_SUB_ZZ(A, @Z@_OF_R(B))
  END FUNCTION @Z@_SUB_ZR

  ELEMENTAL FUNCTION @Z@_SUB_RZ(A, B) RESULT(RES)
    REAL(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_SUB_ZZ(@Z@_OF_R(A), B)
  END FUNCTION @Z@_SUB_RZ

  ELEMENTAL FUNCTION @Z@_SUB_ZC(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    COMPLEX(DP), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_SUB_ZZ(A, @Z@_OF_C(B))
  END FUNCTION @Z@_SUB_ZC

  ELEMENTAL FUNCTION @Z@_SUB_CZ(A, B) RESULT(RES)
    COMPLEX(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_SUB_ZZ(@Z@_OF_C(A), B)
  END FUNCTION @Z@_SUB_CZ

  ELEMENTAL FUNCTION @Z@_SUB_ZI(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_SUB_ZZ(A, @Z@_OF_I(B))
  END FUNCTION @Z@_SUB_ZI

  ELEMENTAL FUNCTION @Z@_SUB_IZ(A, B) RESULT(RES)
    INTEGER, INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_SUB_ZZ(@Z@_OF_I(A), B)
  END FUNCTION @Z@_SUB_IZ

  ELEMENTAL FUNCTION @Z@_SUB_TC(A, B) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: A
    COMPLEX(DP), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_SUB_ZZ(@Z@_OF_T(A), @Z@_OF_C(B))
  END FUNCTION @Z@_SUB_TC

  ELEMENTAL FUNCTION @Z@_SUB_CT(A, B) RESULT(RES)
    COMPLEX(DP), INTENT(IN) :: A
    TYPE(@T@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_SUB_ZZ(@Z@_OF_C(A), @Z@_OF_T(B))
  END FUNCTION @Z@_SUB_CT

  ELEMENTAL FUNCTION @Z@_MUL_ZT(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    TYPE(@T@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_MUL_ZZ(A, @Z@_OF_T(B))
  END FUNCTION @Z@_MUL_ZT

  ELEMENTAL FUNCTION @Z@_MUL_TZ(A, B) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_MUL_ZZ(@Z@_OF_T(A), B)
  END FUNCTION @Z@_MUL_TZ

  ELEMENTAL FUNCTION @Z@_MUL_ZR(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    REAL(DP), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_MUL_ZZ(A, @Z@_OF_R(B))
  END FUNCTION @Z@_MUL_ZR

  ELEMENTAL FUNCTION @Z@_MUL_RZ(A, B) RESULT(RES)
    REAL(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_MUL_ZZ(@Z@_OF_R(A), B)
  END FUNCTION @Z@_MUL_RZ

  ELEMENTAL FUNCTION @Z@_MUL_ZC(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    COMPLEX(DP), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_MUL_ZZ(A, @Z@_OF_C(B))
  END FUNCTION @Z@_MUL_ZC

  ELEMENTAL FUNCTION @Z@_MUL_CZ(A, B) RESULT(RES)
    COMPLEX(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_MUL_ZZ(@Z@_OF_C(A), B)
  END FUNCTION @Z@_MUL_CZ

  ELEMENTAL FUNCTION @Z@_MUL_ZI(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_MUL_ZZ(A, @Z@_OF_I(B))
  END FUNCTION @Z@_MUL_ZI

  ELEMENTAL FUNCTION @Z@_MUL_IZ(A, B) RESULT(RES)
    INTEGER, INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_MUL_ZZ(@Z@_OF_I(A), B)
  END FUNCTION @Z@_MUL_IZ

  ELEMENTAL FUNCTION @Z@_MUL_TC(A, B) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: A
    COMPLEX(DP), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_MUL_ZZ(@Z@_OF_T(A), @Z@_OF_C(B))
  END FUNCTION @Z@_MUL_TC

  ELEMENTAL FUNCTION @Z@_MUL_CT(A, B) RESULT(RES)
    COMPLEX(DP), INTENT(IN) :: A
    TYPE(@T@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_MUL_ZZ(@Z@_OF_C(A), @Z@_OF_T(B))
  END FUNCTION @Z@_MUL_CT

  ELEMENTAL FUNCTION @Z@_DIV_ZT(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    TYPE(@T@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_DIV_ZZ(A, @Z@_OF_T(B))
  END FUNCTION @Z@_DIV_ZT

  ELEMENTAL FUNCTION @Z@_DIV_TZ(A, B) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_DIV_ZZ(@Z@_OF_T(A), B)
  END FUNCTION @Z@_DIV_TZ

  ELEMENTAL FUNCTION @Z@_DIV_ZR(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    REAL(DP), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_DIV_ZZ(A, @Z@_OF_R(B))
  END FUNCTION @Z@_DIV_ZR

  ELEMENTAL FUNCTION @Z@_DIV_RZ(A, B) RESULT(RES)
    REAL(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_DIV_ZZ(@Z@_OF_R(A), B)
  END FUNCTION @Z@_DIV_RZ

  ELEMENTAL FUNCTION @Z@_DIV_ZC(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    COMPLEX(DP), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_DIV_ZZ(A, @Z@_OF_C(B))
  END FUNCTION @Z@_DIV_ZC

  ELEMENTAL FUNCTION @Z@_DIV_CZ(A, B) RESULT(RES)
    COMPLEX(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_DIV_ZZ(@Z@_OF_C(A), B)
  END FUNCTION @Z@_DIV_CZ

  ELEMENTAL FUNCTION @Z@_DIV_ZI(A, B) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_DIV_ZZ(A, @Z@_OF_I(B))
  END FUNCTION @Z@_DIV_ZI

  ELEMENTAL FUNCTION @Z@_DIV_IZ(A, B) RESULT(RES)
    INTEGER, INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_DIV_ZZ(@Z@_OF_I(A), B)
  END FUNCTION @Z@_DIV_IZ

  ELEMENTAL FUNCTION @Z@_DIV_TC(A, B) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: A
    COMPLEX(DP), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_DIV_ZZ(@Z@_OF_T(A), @Z@_OF_C(B))
  END FUNCTION @Z@_DIV_TC

  ELEMENTAL FUNCTION @Z@_DIV_CT(A, B) RESULT(RES)
    COMPLEX(DP), INTENT(IN) :: A
    TYPE(@T@), INTENT(IN) :: B
    TYPE(@Z@) :: RES
    RES = @Z@_DIV_ZZ(@Z@_OF_C(A), @Z@_OF_T(B))
  END FUNCTION @Z@_DIV_CT

  ! ---------------------------------------------------------------- power
  ! Integer exponent: repeated squaring, as the compiler's run time does.
  ELEMENTAL FUNCTION @Z@_POW_ZI(A, N) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: N
    TYPE(@Z@) :: RES, BASE
    INTEGER :: M
    RES%RE = 1.0_DP
    RES%IM = 0.0_DP
    BASE = A
    M = ABS(N)
    DO WHILE (M > 0)
      IF (MOD(M, 2) == 1) RES = @Z@_MUL_ZZ(RES, BASE)
      M = M / 2
      IF (M > 0) BASE = @Z@_MUL_ZZ(BASE, BASE)
    END DO
    IF (N < 0) RES = @Z@_DIV_ZZ(@Z@_OF_R(1.0_DP), RES)
  END FUNCTION @Z@_POW_ZI

  ! General exponent: principal value EXP(W*LOG(Z)). A zero base is not
  ! differentiable for a non-integer exponent; the value is the intrinsic's
  ! (0) and the derivative is zero.
  ELEMENTAL FUNCTION @Z@_POW_ZZ(A, W) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A, W
    TYPE(@Z@) :: RES
    IF (@Z@_IS_ZERO(A)) THEN
      RES%RE = 0.0_DP
      RES%IM = 0.0_DP
    ELSE
      RES = @Z@_EXP(@Z@_MUL_ZZ(W, @Z@_LOG(A)))
    END IF
  END FUNCTION @Z@_POW_ZZ

  ELEMENTAL FUNCTION @Z@_POW_ZR(A, E) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    REAL(DP), INTENT(IN) :: E
    TYPE(@Z@) :: RES
    IF (E == AINT(E) .AND. ABS(E) <= 64.0_DP) THEN
      RES = @Z@_POW_ZI(A, INT(E))
    ELSE
      RES = @Z@_POW_ZZ(A, @Z@_OF_R(E))
    END IF
  END FUNCTION @Z@_POW_ZR

  ELEMENTAL FUNCTION @Z@_POW_ZT(A, E) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    TYPE(@T@), INTENT(IN) :: E
    TYPE(@Z@) :: RES
    RES = @Z@_POW_ZZ(A, @Z@_OF_T(E))
  END FUNCTION @Z@_POW_ZT

  ELEMENTAL FUNCTION @Z@_POW_ZC(A, E) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: A
    COMPLEX(DP), INTENT(IN) :: E
    TYPE(@Z@) :: RES
    RES = @Z@_POW_ZZ(A, @Z@_OF_C(E))
  END FUNCTION @Z@_POW_ZC

  ELEMENTAL FUNCTION @Z@_POW_RZ(A, W) RESULT(RES)
    REAL(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: W
    TYPE(@Z@) :: RES
    RES = @Z@_POW_ZZ(@Z@_OF_R(A), W)
  END FUNCTION @Z@_POW_RZ

  ELEMENTAL FUNCTION @Z@_POW_TZ(A, W) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: W
    TYPE(@Z@) :: RES
    RES = @Z@_POW_ZZ(@Z@_OF_T(A), W)
  END FUNCTION @Z@_POW_TZ

  ELEMENTAL FUNCTION @Z@_POW_CZ(A, W) RESULT(RES)
    COMPLEX(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: W
    TYPE(@Z@) :: RES
    RES = @Z@_POW_ZZ(@Z@_OF_C(A), W)
  END FUNCTION @Z@_POW_CZ

  ! ----------------------------------------------------------- comparison
  ! Values only, like the real OTI relations.
  ELEMENTAL LOGICAL FUNCTION @Z@_EQ_ZZ(A, B)
    TYPE(@Z@), INTENT(IN) :: A, B
    @Z@_EQ_ZZ = REAL(A%RE) == REAL(B%RE) .AND. REAL(A%IM) == REAL(B%IM)
  END FUNCTION @Z@_EQ_ZZ

  ELEMENTAL LOGICAL FUNCTION @Z@_EQ_ZC(A, B)
    TYPE(@Z@), INTENT(IN) :: A
    COMPLEX(DP), INTENT(IN) :: B
    @Z@_EQ_ZC = REAL(A%RE) == REAL(B, DP) .AND. REAL(A%IM) == AIMAG(B)
  END FUNCTION @Z@_EQ_ZC

  ELEMENTAL LOGICAL FUNCTION @Z@_EQ_CZ(A, B)
    COMPLEX(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    @Z@_EQ_CZ = @Z@_EQ_ZC(B, A)
  END FUNCTION @Z@_EQ_CZ

  ELEMENTAL LOGICAL FUNCTION @Z@_EQ_ZR(A, B)
    TYPE(@Z@), INTENT(IN) :: A
    REAL(DP), INTENT(IN) :: B
    @Z@_EQ_ZR = REAL(A%RE) == B .AND. REAL(A%IM) == 0.0_DP
  END FUNCTION @Z@_EQ_ZR

  ELEMENTAL LOGICAL FUNCTION @Z@_EQ_RZ(A, B)
    REAL(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    @Z@_EQ_RZ = @Z@_EQ_ZR(B, A)
  END FUNCTION @Z@_EQ_RZ

  ELEMENTAL LOGICAL FUNCTION @Z@_NE_ZZ(A, B)
    TYPE(@Z@), INTENT(IN) :: A, B
    @Z@_NE_ZZ = .NOT. @Z@_EQ_ZZ(A, B)
  END FUNCTION @Z@_NE_ZZ

  ELEMENTAL LOGICAL FUNCTION @Z@_NE_ZC(A, B)
    TYPE(@Z@), INTENT(IN) :: A
    COMPLEX(DP), INTENT(IN) :: B
    @Z@_NE_ZC = .NOT. @Z@_EQ_ZC(A, B)
  END FUNCTION @Z@_NE_ZC

  ELEMENTAL LOGICAL FUNCTION @Z@_NE_CZ(A, B)
    COMPLEX(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    @Z@_NE_CZ = .NOT. @Z@_EQ_ZC(B, A)
  END FUNCTION @Z@_NE_CZ

  ELEMENTAL LOGICAL FUNCTION @Z@_NE_ZR(A, B)
    TYPE(@Z@), INTENT(IN) :: A
    REAL(DP), INTENT(IN) :: B
    @Z@_NE_ZR = .NOT. @Z@_EQ_ZR(A, B)
  END FUNCTION @Z@_NE_ZR

  ELEMENTAL LOGICAL FUNCTION @Z@_NE_RZ(A, B)
    REAL(DP), INTENT(IN) :: A
    TYPE(@Z@), INTENT(IN) :: B
    @Z@_NE_RZ = .NOT. @Z@_EQ_ZR(B, A)
  END FUNCTION @Z@_NE_RZ

  ! --------------------------------------------------------- constructors
  ELEMENTAL FUNCTION @Z@_FROM_TT(X, Y) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: X, Y
    TYPE(@Z@) :: RES
    RES%RE = X
    RES%IM = Y
  END FUNCTION @Z@_FROM_TT

  ELEMENTAL FUNCTION @Z@_FROM_TR(X, Y) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: X
    REAL(DP), INTENT(IN) :: Y
    TYPE(@Z@) :: RES
    RES%RE = X
    RES%IM = Y
  END FUNCTION @Z@_FROM_TR

  ELEMENTAL FUNCTION @Z@_FROM_RT(X, Y) RESULT(RES)
    REAL(DP), INTENT(IN) :: X
    TYPE(@T@), INTENT(IN) :: Y
    TYPE(@Z@) :: RES
    RES%RE = X
    RES%IM = Y
  END FUNCTION @Z@_FROM_RT

  ELEMENTAL FUNCTION @Z@_FROM_TI(X, Y) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: X
    INTEGER, INTENT(IN) :: Y
    TYPE(@Z@) :: RES
    RES%RE = X
    RES%IM = REAL(Y, DP)
  END FUNCTION @Z@_FROM_TI

  ELEMENTAL FUNCTION @Z@_FROM_IT(X, Y) RESULT(RES)
    INTEGER, INTENT(IN) :: X
    TYPE(@T@), INTENT(IN) :: Y
    TYPE(@Z@) :: RES
    RES%RE = REAL(X, DP)
    RES%IM = Y
  END FUNCTION @Z@_FROM_IT

  ELEMENTAL FUNCTION @Z@_FROM_T(X) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: X
    TYPE(@Z@) :: RES
    RES%RE = X
    RES%IM = 0.0_DP
  END FUNCTION @Z@_FROM_T

  ELEMENTAL FUNCTION @Z@_FROM_Z(X) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: X
    TYPE(@Z@) :: RES
    RES = X
  END FUNCTION @Z@_FROM_Z

  ! CMPLX(X, Y, KIND): the kind is not a precision choice here -- the parts are
  ! OTI numbers in REAL(DP) -- so it is accepted and ignored.
  ELEMENTAL FUNCTION @Z@_FROM_TT_K(X, Y, KIND) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: X, Y
    INTEGER, INTENT(IN) :: KIND
    TYPE(@Z@) :: RES
    RES%RE = X
    RES%IM = Y
  END FUNCTION @Z@_FROM_TT_K

  ELEMENTAL FUNCTION @Z@_FROM_TR_K(X, Y, KIND) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: X
    REAL(DP), INTENT(IN) :: Y
    INTEGER, INTENT(IN) :: KIND
    TYPE(@Z@) :: RES
    RES%RE = X
    RES%IM = Y
  END FUNCTION @Z@_FROM_TR_K

  ELEMENTAL FUNCTION @Z@_FROM_RT_K(X, Y, KIND) RESULT(RES)
    REAL(DP), INTENT(IN) :: X
    TYPE(@T@), INTENT(IN) :: Y
    INTEGER, INTENT(IN) :: KIND
    TYPE(@Z@) :: RES
    RES%RE = X
    RES%IM = Y
  END FUNCTION @Z@_FROM_RT_K

  ELEMENTAL FUNCTION @Z@_FROM_Z_K(X, KIND) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: X
    INTEGER, INTENT(IN) :: KIND
    TYPE(@Z@) :: RES
    RES = X
  END FUNCTION @Z@_FROM_Z_K

  ! ---------------------------------------------------- parts (real maps)
  ELEMENTAL FUNCTION @Z@_DBLE_Z(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@T@) :: RES
    RES = Z%RE
  END FUNCTION @Z@_DBLE_Z

  ! DBLE of a real OTI is the number itself, derivative and all.
  ELEMENTAL FUNCTION @Z@_DBLE_T(X) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: X
    TYPE(@T@) :: RES
    RES = X
  END FUNCTION @Z@_DBLE_T

  ELEMENTAL FUNCTION @Z@_REAL_Z(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@T@) :: RES
    RES = Z%RE
  END FUNCTION @Z@_REAL_Z

  ELEMENTAL FUNCTION @Z@_REAL_ZK(Z, KIND) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    INTEGER, INTENT(IN) :: KIND
    TYPE(@T@) :: RES
    RES = Z%RE
  END FUNCTION @Z@_REAL_ZK

  ELEMENTAL FUNCTION @Z@_AIMAG(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@T@) :: RES
    RES = Z%IM
  END FUNCTION @Z@_AIMAG

  ELEMENTAL FUNCTION @Z@_CONJG(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@Z@) :: RES
    RES%RE = Z%RE
    RES%IM = -Z%IM
  END FUNCTION @Z@_CONJG

  ! |z| = hypot(RE, IM), scaled by the larger part so nothing overflows and
  ! the square root is never taken at 0 unless z itself is 0 (cone point:
  ! value 0, derivative 0 -- the real OTI ABS convention at 0).
  ELEMENTAL FUNCTION @Z@_ABS(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@T@) :: RES, Q
    REAL(DP) :: A, B
    A = REAL(Z%RE)
    B = REAL(Z%IM)
    IF (A == 0.0_DP .AND. B == 0.0_DP) THEN
      RES = 0.0_DP
    ELSE IF (ABS(A) >= ABS(B)) THEN
      Q = Z%IM / Z%RE
      RES = ABS(Z%RE) * (1.0_DP + Q*Q)**0.5_DP
    ELSE
      Q = Z%RE / Z%IM
      RES = ABS(Z%IM) * (1.0_DP + Q*Q)**0.5_DP
    END IF
  END FUNCTION @Z@_ABS

  ! ------------------------------------------------- ATAN2 over real OTI
  ELEMENTAL FUNCTION @T@_ATAN2_TT(Y, X) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: Y, X
    TYPE(@T@) :: RES
    REAL(DP) :: XV, YV
    XV = REAL(X)
    YV = REAL(Y)
    IF (XV == 0.0_DP .AND. YV == 0.0_DP) THEN
      RES = ATAN2(YV, XV)
    ELSE IF (ABS(XV) >= ABS(YV)) THEN
      RES = ATAN(Y / X)
      IF (XV < 0.0_DP) RES = RES + SIGN(ZPI, YV)
    ELSE
      RES = SIGN(0.5_DP*ZPI, YV) - ATAN(X / Y)
    END IF
  END FUNCTION @T@_ATAN2_TT

  ELEMENTAL FUNCTION @T@_ATAN2_TR(Y, X) RESULT(RES)
    TYPE(@T@), INTENT(IN) :: Y
    REAL(DP), INTENT(IN) :: X
    TYPE(@T@) :: RES
    RES = @T@_ATAN2_TT(Y, @Z@_TR(X))
  END FUNCTION @T@_ATAN2_TR

  ELEMENTAL FUNCTION @T@_ATAN2_RT(Y, X) RESULT(RES)
    REAL(DP), INTENT(IN) :: Y
    TYPE(@T@), INTENT(IN) :: X
    TYPE(@T@) :: RES
    RES = @T@_ATAN2_TT(@Z@_TR(Y), X)
  END FUNCTION @T@_ATAN2_RT

  ! ----------------------------------------------- holomorphic functions
  ! Principal square root, cut on the negative real axis; the sign of a zero
  ! imaginary part selects the side, as for the intrinsic.
  ELEMENTAL FUNCTION @Z@_SQRT(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@Z@) :: RES
    TYPE(@T@) :: R, T
    REAL(DP) :: A, B
    A = REAL(Z%RE)
    B = REAL(Z%IM)
    IF (A == 0.0_DP .AND. B == 0.0_DP) THEN
      RES%RE = 0.0_DP
      RES%IM = Z%IM * 0.0_DP
      RETURN
    END IF
    R = @Z@_ABS(Z)
    IF (A >= 0.0_DP) THEN
      T = ((R + Z%RE) * 0.5_DP)**0.5_DP
      RES%RE = T
      RES%IM = Z%IM / (2.0_DP*T)
    ELSE
      T = ((R - Z%RE) * 0.5_DP)**0.5_DP
      IF (SIGN(1.0_DP, B) < 0.0_DP) T = -T
      RES%IM = T
      RES%RE = Z%IM / (2.0_DP*T)
    END IF
  END FUNCTION @Z@_SQRT

  ! Principal logarithm: LOG|z| + i ARG(z), ARG in (-pi, pi].
  ELEMENTAL FUNCTION @Z@_LOG(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@Z@) :: RES
    RES%RE = LOG(@Z@_ABS(Z))
    RES%IM = @T@_ATAN2_TT(Z%IM, Z%RE)
  END FUNCTION @Z@_LOG

  ELEMENTAL FUNCTION @Z@_EXP(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@Z@) :: RES
    TYPE(@T@) :: EA
    EA = EXP(Z%RE)
    RES%RE = EA * COS(Z%IM)
    RES%IM = EA * SIN(Z%IM)
  END FUNCTION @Z@_EXP

  ELEMENTAL FUNCTION @Z@_SIN(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@Z@) :: RES
    RES%RE = SIN(Z%RE) * COSH(Z%IM)
    RES%IM = COS(Z%RE) * SINH(Z%IM)
  END FUNCTION @Z@_SIN

  ELEMENTAL FUNCTION @Z@_COS(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@Z@) :: RES
    RES%RE = COS(Z%RE) * COSH(Z%IM)
    RES%IM = -(SIN(Z%RE) * SINH(Z%IM))
  END FUNCTION @Z@_COS

  ELEMENTAL FUNCTION @Z@_TAN(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@Z@) :: RES
    RES = @Z@_DIV_ZZ(@Z@_SIN(Z), @Z@_COS(Z))
  END FUNCTION @Z@_TAN

  ELEMENTAL FUNCTION @Z@_SINH(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@Z@) :: RES
    RES%RE = SINH(Z%RE) * COS(Z%IM)
    RES%IM = COSH(Z%RE) * SIN(Z%IM)
  END FUNCTION @Z@_SINH

  ELEMENTAL FUNCTION @Z@_COSH(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    TYPE(@Z@) :: RES
    RES%RE = COSH(Z%RE) * COS(Z%IM)
    RES%IM = SINH(Z%RE) * SIN(Z%IM)
  END FUNCTION @Z@_COSH

  ! ------------------------------------------------------------- inspection
  ! The plain complex value, derivatives dropped. For diagnostics only: the
  ! transform never uses it on a value that reaches STRESS.
  ELEMENTAL FUNCTION @Z@_CVALUE(Z) RESULT(RES)
    TYPE(@Z@), INTENT(IN) :: Z
    COMPLEX(DP) :: RES
    RES = CMPLX(REAL(Z%RE), REAL(Z%IM), DP)
  END FUNCTION @Z@_CVALUE

END MODULE oti_complex
"""


def generate_complex_oti_module(module_name: str, type_name: str) -> str:
    """Fortran source of ``oti_complex`` over the real OTI module ``module_name``.

    The module is written only in terms of the real OTI module's generic
    operators and elemental functions, so it serves any NTENS and any order
    the real module was generated for.
    """
    if not module_name or not type_name:
        raise ValueError("module_name and type_name are required")
    return (_TEMPLATE.replace("@Z@", complex_type_name(type_name))
            .replace("@T@", type_name.upper())
            .replace("@M@", module_name)
            .lstrip("\n"))


def write_complex_oti_module(output_dir: Path, module_name: str, type_name: str) -> Path:
    """Write ``oti_complex.f90`` into ``output_dir`` and return its path."""
    path = Path(output_dir) / COMPLEX_MODULE_FILE
    path.write_text(generate_complex_oti_module(module_name, type_name), encoding="utf-8")
    return path
