      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
C     Orthotropic linear elasticity, 9 independent stiffness constants.
C     Voigt order (11,22,33,12,13,23). Small strain. Self-contained.
      INCLUDE 'ABA_PARAM.INC'
      CHARACTER*80 CMNAME
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)
      PARAMETER (ZERO=0.D0)
      DIMENSION DS(6)
      INTEGER K1,K2
      C11 = PROPS(1)
      C12 = PROPS(2)
      C13 = PROPS(3)
      C22 = PROPS(4)
      C23 = PROPS(5)
      C33 = PROPS(6)
      C44 = PROPS(7)
      C55 = PROPS(8)
      C66 = PROPS(9)
      DO K1=1,NTENS
        DO K2=1,NTENS
          DDSDDE(K1,K2)=ZERO
        END DO
      END DO
      DDSDDE(1,1)=C11
      DDSDDE(1,2)=C12
      DDSDDE(2,1)=C12
      DDSDDE(1,3)=C13
      DDSDDE(3,1)=C13
      DDSDDE(2,2)=C22
      DDSDDE(2,3)=C23
      DDSDDE(3,2)=C23
      DDSDDE(3,3)=C33
      DDSDDE(4,4)=C44
      DDSDDE(5,5)=C55
      DDSDDE(6,6)=C66
      DO K1=1,NTENS
        DS(K1)=ZERO
        DO K2=1,NTENS
          DS(K1)=DS(K1)+DDSDDE(K1,K2)*DSTRAN(K2)
        END DO
      END DO
      DO K1=1,NTENS
        STRESS(K1)=STRESS(K1)+DS(K1)
      END DO
      RETURN
      END
