"""Routine-level drivers for corpus UMATs: original (real) and OTI (lifted).

Two Fortran programs, both generated here, both reading the same plain-text
configuration (``cf_config.txt``) so the original routine and the OTI build see
byte-identical inputs.

``cf_real_driver``
    Calls a routine with the STANDARD Abaqus interface (all REAL(8)). Linked
    either against the ORIGINAL source (the reference) or against the store's
    DSTRAN-seeded OTI build, whose interface is also real (it returns DDSDDE).
    In one process it runs

    * the base history, increment by increment (``B`` records),
    * LOCAL perturbations: at every increment, for every requested
      perturbation and sign, one call from the RESTORED incoming state --
      STRESS, STATEV, STRAN, SSE/SPD/SCD, TIME copied back from the base
      trajectory; DDSDDE, DDSDDT, DRPLDE, RPL, DRPLDT zeroed; PNEWDT = 1 --
      (``L`` records),
    * TOTAL perturbations: the whole history re-run from the initial state
      with the perturbation applied (``T`` records).

``cf_oti_driver``
    Calls ``umat_oti`` from the generically lifted build (every REAL argument
    is an OTI number). Seeds are read at run time: PROPS(i), incoming
    STATEV(i), incoming STRESS(i), DSTRAN(j) or a DFGRD1 direction, each onto
    one imaginary direction. Two modes:

    * ``local``: at every increment the incoming state is REAL (the previous
      increment's real parts), the seeds are applied, and the imaginary parts
      of STRESS/STATEV after the call are the LOCAL derivatives.
    * ``total``: PROPS seeds (or initial-STATEV seeds) are applied at the
      start and the OTI STRESS/STATEV are CARRIED across increments, so the
      imaginary parts at increment n are the TOTAL derivatives through the
      prescribed-strain history.
"""
from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Sequence

import numpy as np

CONFIG_FILE = "cf_config.txt"
PERT_FILE = "cf_perturbations.txt"
SEED_FILE = "cf_seeds.txt"
REAL_OUT = "cf_real_out.txt"
OTI_OUT = "cf_oti_out.txt"

KIND = {"none": 0, "props": 1, "statev": 2, "dstran": 3, "dfgrd1": 4, "stress": 5}

_COMMON_DECL = """  INTEGER :: NTENS,NSTATV,NPROPS,NDI,NSHR,NINC,CALLSDV,I,J,K,INC,U,UO,IOS
  INTEGER :: NOEL,NPT,LAYER,KSPT,KSTEP,KINC
  CHARACTER(80) :: CMNAME
  REAL(8), ALLOCATABLE :: PROPS0(:),STATEV0(:),DSTRANH(:,:),F0H(:,:,:),F1H(:,:,:)
  REAL(8), ALLOCATABLE :: DROTH(:,:,:),DTH(:),TEMPH(:),DTEMPH(:)
  REAL(8) :: COORDS0(3)
"""

_READ_CONFIG = """  OPEN(NEWUNIT=U,FILE='%(config)s',STATUS='OLD',ACTION='READ',IOSTAT=IOS)
  IF (IOS .NE. 0) STOP 2
  READ(U,*) NTENS,NSTATV,NPROPS,NDI,NSHR,NINC,CALLSDV
  READ(U,'(A)') CMNAME
  ALLOCATE(PROPS0(MAX(NPROPS,1)),STATEV0(MAX(NSTATV,1)))
  ALLOCATE(DSTRANH(NTENS,NINC),F0H(3,3,NINC),F1H(3,3,NINC),DROTH(3,3,NINC))
  ALLOCATE(DTH(NINC),TEMPH(NINC),DTEMPH(NINC))
  PROPS0=0.0_8; STATEV0=0.0_8
  READ(U,*) (PROPS0(I),I=1,MAX(NPROPS,1))
  READ(U,*) (STATEV0(I),I=1,MAX(NSTATV,1))
  READ(U,*) (COORDS0(I),I=1,3)
  DO INC=1,NINC
    READ(U,*) DTH(INC),TEMPH(INC),DTEMPH(INC)
    READ(U,*) (DSTRANH(I,INC),I=1,NTENS)
    READ(U,*) ((F0H(I,J,INC),J=1,3),I=1,3)
    READ(U,*) ((F1H(I,J,INC),J=1,3),I=1,3)
    READ(U,*) ((DROTH(I,J,INC),J=1,3),I=1,3)
  END DO
  CLOSE(U)
"""

REAL_DRIVER = """PROGRAM cf_real_driver
! Generated by umat_oti.corpus_features.drivers. Standard-interface routine,
! base history + local (restored incoming state) + total (re-run) perturbations.
  IMPLICIT NONE
%(common)s
  INTEGER :: NPERT,IP,SG,NLOC,NTOT
  INTEGER, ALLOCATABLE :: PMODE(:),PKIND(:),PIDX(:)
  REAL(8), ALLOCATABLE :: PSTEP(:),PDIR(:,:,:)
  REAL(8), ALLOCATABLE :: STRESS(:),STATEV(:),DDSDDE(:,:),STRAN(:),DSTRAN(:)
  REAL(8), ALLOCATABLE :: PROPS(:),DDSDDT(:),DRPLDE(:)
  REAL(8), ALLOCATABLE :: S_IN(:),X_IN(:),STRAN_IN(:),SB(:),XB(:)
  REAL(8) :: SSE,SPD,SCD,RPL,DRPLDT,PNEWDT,CELENT,DTIME,TEMP,DTEMP
  REAL(8) :: SSE_IN,SPD_IN,SCD_IN,SSEB,SPDB,SCDB
  REAL(8) :: TIME(2),TIME_IN(2),PREDEF(1),DPRED(1),COORDS(3),DROT(3,3)
  REAL(8) :: DFGRD0(3,3),DFGRD1(3,3),ZDIR(3,3)
  INTEGER :: KSTEPA(4)

%(read)s
  OPEN(NEWUNIT=U,FILE='%(pert)s',STATUS='OLD',ACTION='READ',IOSTAT=IOS)
  NPERT=0
  IF (IOS .EQ. 0) THEN
    READ(U,*) NPERT
  END IF
  ALLOCATE(PMODE(MAX(NPERT,1)),PKIND(MAX(NPERT,1)),PIDX(MAX(NPERT,1)))
  ALLOCATE(PSTEP(MAX(NPERT,1)),PDIR(3,3,MAX(NPERT,1)))
  DO IP=1,NPERT
    READ(U,*) PMODE(IP),PKIND(IP),PIDX(IP),PSTEP(IP),((PDIR(I,J,IP),J=1,3),I=1,3)
  END DO
  IF (IOS .EQ. 0) CLOSE(U)

  ALLOCATE(STRESS(NTENS),STATEV(MAX(NSTATV,1)),DDSDDE(NTENS,NTENS))
  ALLOCATE(STRAN(NTENS),DSTRAN(NTENS),PROPS(MAX(NPROPS,1)))
  ALLOCATE(DDSDDT(NTENS),DRPLDE(NTENS))
  ALLOCATE(S_IN(NTENS),X_IN(MAX(NSTATV,1)),STRAN_IN(NTENS),SB(NTENS),XB(MAX(NSTATV,1)))
  ZDIR=0.0_8

  STATEV=STATEV0
  IF (CALLSDV .EQ. 1) THEN
%(sdvini)s
  END IF
  STATEV0=STATEV

  OPEN(NEWUNIT=UO,FILE='%(out)s',STATUS='REPLACE',ACTION='WRITE')
  WRITE(UO,'(A,*(1X,ES25.16E3))') 'I',(STATEV0(I),I=1,MAX(NSTATV,1))

! ---------------- base history + local perturbations ----------------
  CALL RESET_HISTORY()
  DO INC=1,NINC
    CALL EVAL(INC,0,0,0.0_8,ZDIR)
    WRITE(UO,'(A,1X,I0,*(1X,ES25.16E3))') 'B',INC,(STRESS(I),I=1,NTENS), &
      (STATEV(I),I=1,MAX(NSTATV,1)),((DDSDDE(I,J),J=1,NTENS),I=1,NTENS),SSE,SPD,SCD,PNEWDT
    SB=STRESS; XB=STATEV; SSEB=SSE; SPDB=SPD; SCDB=SCD
    NLOC=0
    DO IP=1,NPERT
      IF (PMODE(IP) .NE. 1) CYCLE
      NLOC=NLOC+1
      DO SG=1,-1,-2
        CALL EVAL(INC,PKIND(IP),PIDX(IP),SG*PSTEP(IP),PDIR(:,:,IP))
        WRITE(UO,'(A,3(1X,I0),*(1X,ES25.16E3))') 'L',INC,IP,SG,(STRESS(I),I=1,NTENS), &
          (STATEV(I),I=1,MAX(NSTATV,1)),PNEWDT
      END DO
    END DO
    IF (NLOC .GT. 0) THEN
      ! hidden-state gate: the unperturbed call replayed after the block
      CALL EVAL(INC,0,0,0.0_8,ZDIR)
      WRITE(UO,'(A,1X,I0,*(1X,ES25.16E3))') 'R',INC,(STRESS(I),I=1,NTENS), &
        (STATEV(I),I=1,MAX(NSTATV,1)),((DDSDDE(I,J),J=1,NTENS),I=1,NTENS),SSE,SPD,SCD,PNEWDT
    END IF
    S_IN=SB; X_IN=XB; SSE_IN=SSEB; SPD_IN=SPDB; SCD_IN=SCDB
    STRAN_IN=STRAN_IN+DSTRANH(:,INC)
    TIME_IN=TIME_IN+DTH(INC)
  END DO

! ---------------- total perturbations: whole history re-run ----------------
  NTOT=0
  DO IP=1,NPERT
    IF (PMODE(IP) .NE. 2) CYCLE
    DO SG=1,-1,-2
      CALL RESET_HISTORY()
      IF (PKIND(IP) .EQ. 2) X_IN(PIDX(IP))=X_IN(PIDX(IP))+SG*PSTEP(IP)
      DO INC=1,NINC
        IF (PKIND(IP) .EQ. 2) THEN
          CALL EVAL(INC,0,0,0.0_8,ZDIR)
        ELSE
          CALL EVAL(INC,PKIND(IP),PIDX(IP),SG*PSTEP(IP),PDIR(:,:,IP))
        END IF
        WRITE(UO,'(A,3(1X,I0),*(1X,ES25.16E3))') 'T',IP,SG,INC,(STRESS(I),I=1,NTENS), &
          (STATEV(I),I=1,MAX(NSTATV,1)),PNEWDT
        S_IN=STRESS; X_IN=STATEV; SSE_IN=SSE; SPD_IN=SPD; SCD_IN=SCD
        STRAN_IN=STRAN_IN+DSTRANH(:,INC)
        TIME_IN=TIME_IN+DTH(INC)
      END DO
    END DO
    ! hidden-state gate: the first unperturbed call replayed after the block
    CALL RESET_HISTORY()
    CALL EVAL(1,0,0,0.0_8,ZDIR)
    WRITE(UO,'(A,1X,I0,*(1X,ES25.16E3))') 'Q',IP,(STRESS(I),I=1,NTENS), &
      (STATEV(I),I=1,MAX(NSTATV,1)),((DDSDDE(I,J),J=1,NTENS),I=1,NTENS),SSE,SPD,SCD,PNEWDT
    NTOT=NTOT+1
  END DO

! ---------------- hidden-state gate: an h=0 total re-run ----------------
  IF (NTOT .GT. 0) THEN
    CALL RESET_HISTORY()
    DO INC=1,NINC
      CALL EVAL(INC,0,0,0.0_8,ZDIR)
      WRITE(UO,'(A,1X,I0,*(1X,ES25.16E3))') 'Z',INC,(STRESS(I),I=1,NTENS), &
        (STATEV(I),I=1,MAX(NSTATV,1)),((DDSDDE(I,J),J=1,NTENS),I=1,NTENS),SSE,SPD,SCD,PNEWDT
      S_IN=STRESS; X_IN=STATEV; SSE_IN=SSE; SPD_IN=SPD; SCD_IN=SCD
      STRAN_IN=STRAN_IN+DSTRANH(:,INC)
      TIME_IN=TIME_IN+DTH(INC)
    END DO
  END IF
  CLOSE(UO)

CONTAINS

  SUBROUTINE RESET_HISTORY()
    S_IN=0.0_8; X_IN=STATEV0; STRAN_IN=0.0_8
    SSE_IN=0.0_8; SPD_IN=0.0_8; SCD_IN=0.0_8; TIME_IN=0.0_8
  END SUBROUTINE RESET_HISTORY

  SUBROUTINE EVAL(INCR,KND,IDX,H,DIRN)
    INTEGER, INTENT(IN) :: INCR,KND,IDX
    REAL(8), INTENT(IN) :: H,DIRN(3,3)
    STRESS=S_IN; STATEV=X_IN; STRAN=STRAN_IN; DSTRAN=DSTRANH(:,INCR)
    PROPS=PROPS0; DFGRD0=F0H(:,:,INCR); DFGRD1=F1H(:,:,INCR); DROT=DROTH(:,:,INCR)
    SSE=SSE_IN; SPD=SPD_IN; SCD=SCD_IN; TIME=TIME_IN
    DDSDDE=0.0_8; DDSDDT=0.0_8; DRPLDE=0.0_8; RPL=0.0_8; DRPLDT=0.0_8
    PREDEF=0.0_8; DPRED=0.0_8; PNEWDT=1.0_8; CELENT=1.0_8
    DTIME=DTH(INCR); TEMP=TEMPH(INCR); DTEMP=DTEMPH(INCR); COORDS=COORDS0
    NOEL=1; NPT=1; LAYER=1; KSPT=1; KSTEPA=0; KSTEPA(1)=1; KINC=INCR
    SELECT CASE (KND)
    CASE (1)
      PROPS(IDX)=PROPS(IDX)+H
    CASE (2)
      STATEV(IDX)=STATEV(IDX)+H
    CASE (3)
      DSTRAN(IDX)=DSTRAN(IDX)+H
    CASE (4)
      DFGRD1=DFGRD1+H*MATMUL(DIRN,F1H(:,:,INCR))
    CASE (5)
      STRESS(IDX)=STRESS(IDX)+H
    END SELECT
    CALL UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,RPL,DDSDDT,DRPLDE,DRPLDT, &
      STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,NDI,NSHR, &
      NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,CELENT,DFGRD0,DFGRD1, &
      NOEL,NPT,LAYER,KSPT,KSTEPA,KINC)
  END SUBROUTINE EVAL

END PROGRAM cf_real_driver

%(stubs)s"""

_SDVINI = "    IF (ALL(STATEV .EQ. 0.0_8)) CALL SDVINI(STATEV,COORDS0,NSTATV,3,1,1,1,1)"


def quadify(text: str) -> str:
    """The ORIGINAL with its double precision promoted to REAL(16).

    Every REAL*8 / DOUBLE PRECISION / REAL(8) / REAL(KIND=8) (declarations and
    IMPLICIT statements) becomes REAL*16; D-prefixed specific intrinsics
    become generic; DBLE becomes QEXT. Default REAL (binary32) declarations
    and every literal are left exactly as written, so the author's binary32
    quantities stay binary32 and every constant keeps the value the double
    build gives it: the quad build evaluates the same function (Curie-G B2,
    scripts/quadfd.py) with less rounding. A source whose real kind comes
    from a named constant (``REAL(dp)``) is NOT promoted; the primal check
    against the double build is what refuses such a reference.
    """
    t = re.sub(r"(?i)\bdouble\s+precision\b", "REAL*16", text)
    t = re.sub(r"(?i)\breal\s*\*\s*8\b", "REAL*16", t)
    t = re.sub(r"(?i)\breal\s*\(\s*(kind\s*=\s*)?8\s*\)", "REAL(16)", t)
    t = re.sub(r"(?i)\bD(SQRT|EXP|LOG|LOG10|ABS|SIN|COS|TAN|ASIN|ACOS|ATAN|ATAN2|SINH|COSH|TANH|"
               r"SIGN|MOD|MAX1|MIN1|DIM)\s*\(", lambda m: m.group(1) + "(", t)
    t = re.sub(r"(?i)\bDBLE\s*\(", "QEXT(", t)
    return t


def quad_driver(stubs: str, sdvini: bool) -> str:
    """REAL_DRIVER with the routine's state in REAL(16).

    Inputs (configuration, steps, directions) stay REAL(8) and are converted
    exactly; the perturbed input is formed in REAL(16) (x + h exact). Besides
    the usual records it writes ``l``/``t``: perturbed minus base output,
    differenced in REAL(16) before rounding to text.
    """
    src = REAL_DRIVER
    quad_lines = [
        "  REAL(8), ALLOCATABLE :: STRESS(:),STATEV(:),DDSDDE(:,:),STRAN(:),DSTRAN(:)",
        "  REAL(8), ALLOCATABLE :: PROPS(:),DDSDDT(:),DRPLDE(:)",
        "  REAL(8), ALLOCATABLE :: S_IN(:),X_IN(:),STRAN_IN(:),SB(:),XB(:)",
        "  REAL(8) :: SSE,SPD,SCD,RPL,DRPLDT,PNEWDT,CELENT,DTIME,TEMP,DTEMP",
        "  REAL(8) :: SSE_IN,SPD_IN,SCD_IN,SSEB,SPDB,SCDB",
        "  REAL(8) :: TIME(2),TIME_IN(2),PREDEF(1),DPRED(1),COORDS(3),DROT(3,3)"]
    for line in quad_lines:
        assert line in src, line
        src = src.replace(line, line.replace("REAL(8)", "REAL(16)"))
    old = "  REAL(8) :: DFGRD0(3,3),DFGRD1(3,3),ZDIR(3,3)"
    assert old in src
    src = src.replace(old, "  REAL(16) :: DFGRD0(3,3),DFGRD1(3,3)\n  REAL(8) :: ZDIR(3,3)\n"
                           "  REAL(16), ALLOCATABLE :: BS(:,:),BX(:,:)")
    old = "  ALLOCATE(DDSDDT(NTENS),DRPLDE(NTENS))\n"
    assert old in src
    src = src.replace(old, old + "  ALLOCATE(BS(NTENS,NINC),BX(MAX(NSTATV,1),NINC))\n")
    old = "    SB=STRESS; XB=STATEV; SSEB=SSE; SPDB=SPD; SCDB=SCD\n"
    assert old in src
    src = src.replace(old, old + "    BS(:,INC)=STRESS; BX(:,INC)=STATEV\n")
    old = """        WRITE(UO,'(A,3(1X,I0),*(1X,ES25.16E3))') 'L',INC,IP,SG,(STRESS(I),I=1,NTENS), &
          (STATEV(I),I=1,MAX(NSTATV,1)),PNEWDT
"""
    assert old in src
    src = src.replace(old, old + """        WRITE(UO,'(A,3(1X,I0),*(1X,ES25.16E3))') 'l',INC,IP,SG,(STRESS(I)-SB(I),I=1,NTENS), &
          (STATEV(I)-XB(I),I=1,MAX(NSTATV,1))
""")
    old = """        WRITE(UO,'(A,3(1X,I0),*(1X,ES25.16E3))') 'T',IP,SG,INC,(STRESS(I),I=1,NTENS), &
          (STATEV(I),I=1,MAX(NSTATV,1)),PNEWDT
"""
    assert old in src
    src = src.replace(old, old + """        WRITE(UO,'(A,3(1X,I0),*(1X,ES25.16E3))') 't',IP,SG,INC,(STRESS(I)-BS(I,INC),I=1,NTENS), &
          (STATEV(I)-BX(I,INC),I=1,MAX(NSTATV,1))
""")
    return src.replace("PROGRAM cf_real_driver", "PROGRAM cf_quad_driver", 1).replace(
        "END PROGRAM cf_real_driver", "END PROGRAM cf_quad_driver")


OTI_DRIVER = """PROGRAM cf_oti_driver
! Generated by umat_oti.corpus_features.drivers. Lifted (all-OTI) routine,
! seeds read at run time; local (real incoming state) or total (OTI carried).
  USE master_parameters, ONLY: DP
  USE %(module)s
  USE umat_oti_lifted_mod
  IMPLICIT NONE
%(common)s
  INTEGER :: MODE,NSEED,IS
  INTEGER, ALLOCATABLE :: SKIND(:),SIDX(:),SDIR(:)
  REAL(8), ALLOCATABLE :: SMAT(:,:,:)
  TYPE(%(type)s), ALLOCATABLE :: STRESS(:),STATEV(:),DDSDDE(:,:),STRAN(:),DSTRAN(:)
  TYPE(%(type)s), ALLOCATABLE :: PROPS(:),DDSDDT(:),DRPLDE(:)
  TYPE(%(type)s), ALLOCATABLE :: S_CARRY(:),X_CARRY(:)
  TYPE(%(type)s) :: SSE,SPD,SCD,RPL,DRPLDT,PNEWDT,CELENT,DTIME,TEMP,DTEMP
  TYPE(%(type)s) :: TIME(2),PREDEF(1),DPRED(1),COORDS(3),DROT(3,3)
  TYPE(%(type)s) :: DFGRD0(3,3),DFGRD1(3,3),DF(3,3)
  TYPE(%(type)s) :: SSE_C,SPD_C,SCD_C
  REAL(8), ALLOCATABLE :: STRAN_IN(:)
  REAL(8) :: TIME_IN(2)

%(read)s
  OPEN(NEWUNIT=U,FILE='%(seeds)s',STATUS='OLD',ACTION='READ',IOSTAT=IOS)
  IF (IOS .NE. 0) STOP 3
  READ(U,*) MODE,NSEED
  ALLOCATE(SKIND(MAX(NSEED,1)),SIDX(MAX(NSEED,1)),SDIR(MAX(NSEED,1)),SMAT(3,3,MAX(NSEED,1)))
  DO IS=1,NSEED
    READ(U,*) SKIND(IS),SIDX(IS),SDIR(IS),((SMAT(I,J,IS),J=1,3),I=1,3)
  END DO
  CLOSE(U)

  ALLOCATE(STRESS(NTENS),STATEV(MAX(NSTATV,1)),DDSDDE(NTENS,NTENS))
  ALLOCATE(STRAN(NTENS),DSTRAN(NTENS),PROPS(MAX(NPROPS,1)))
  ALLOCATE(DDSDDT(NTENS),DRPLDE(NTENS),S_CARRY(NTENS),X_CARRY(MAX(NSTATV,1)))
  ALLOCATE(STRAN_IN(NTENS))

  S_CARRY=0.0_8; X_CARRY=STATEV0; STRAN_IN=0.0_8; TIME_IN=0.0_8
  SSE_C=0.0_8; SPD_C=0.0_8; SCD_C=0.0_8
  IF (MODE .EQ. 2) THEN
    DO IS=1,NSEED
      IF (SKIND(IS) .EQ. 2) CALL SETIM(X_CARRY(SIDX(IS)),SDIR(IS),1.0_8)
      IF (SKIND(IS) .EQ. 5) CALL SETIM(S_CARRY(SIDX(IS)),SDIR(IS),1.0_8)
    END DO
  END IF

  OPEN(NEWUNIT=UO,FILE='%(out)s',STATUS='REPLACE',ACTION='WRITE')
  DO INC=1,NINC
    IF (MODE .EQ. 1) THEN
      ! local: the incoming state is REAL -- previous real parts only
      STRESS=REAL(S_CARRY); STATEV=REAL(X_CARRY)
      SSE=REAL(SSE_C); SPD=REAL(SPD_C); SCD=REAL(SCD_C)
    ELSE
      STRESS=S_CARRY; STATEV=X_CARRY; SSE=SSE_C; SPD=SPD_C; SCD=SCD_C
    END IF
    STRAN=STRAN_IN; DSTRAN=DSTRANH(:,INC); PROPS=PROPS0
    DFGRD0=F0H(:,:,INC); DFGRD1=F1H(:,:,INC); DROT=DROTH(:,:,INC)
    TIME(1)=TIME_IN(1); TIME(2)=TIME_IN(2)
    DDSDDE=0.0_8; DDSDDT=0.0_8; DRPLDE=0.0_8; RPL=0.0_8; DRPLDT=0.0_8
    PREDEF=0.0_8; DPRED=0.0_8; PNEWDT=1.0_8; CELENT=1.0_8
    DTIME=DTH(INC); TEMP=TEMPH(INC); DTEMP=DTEMPH(INC); COORDS=COORDS0
    NOEL=1; NPT=1; LAYER=1; KSPT=1; KSTEP=1; KINC=INC
    DO IS=1,NSEED
      SELECT CASE (SKIND(IS))
      CASE (1)
        CALL SETIM(PROPS(SIDX(IS)),SDIR(IS),1.0_8)
      CASE (2)
        IF (MODE .EQ. 1) CALL SETIM(STATEV(SIDX(IS)),SDIR(IS),1.0_8)
      CASE (3)
        IF (MODE .EQ. 1) CALL SETIM(DSTRAN(SIDX(IS)),SDIR(IS),1.0_8)
      CASE (4)
        IF (MODE .EQ. 1) THEN
          DO I=1,3
            DO J=1,3
              DF(I,J)=0.0_8
              CALL SETIM(DF(I,J),SDIR(IS),DOT_PRODUCT(SMAT(I,:,IS),F1H(:,J,INC)))
            END DO
          END DO
          DFGRD1=DFGRD1+DF
        END IF
      CASE (5)
        IF (MODE .EQ. 1) CALL SETIM(STRESS(SIDX(IS)),SDIR(IS),1.0_8)
      END SELECT
    END DO
    CALL umat_oti(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,RPL,DDSDDT,DRPLDE,DRPLDT, &
      STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,NDI,NSHR, &
      NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,CELENT,DFGRD0,DFGRD1, &
      NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
    WRITE(UO,'(A,1X,I0,*(1X,ES25.16E3))') 'B',INC,(STRESS(I)%%R,I=1,NTENS), &
      (STATEV(I)%%R,I=1,MAX(NSTATV,1)),((DDSDDE(I,J)%%R,J=1,NTENS),I=1,NTENS), &
      SSE%%R,SPD%%R,SCD%%R,PNEWDT%%R
    WRITE(UO,'(A,1X,I0,*(1X,ES25.16E3))') 'D',INC, &
      ((GETIM(STRESS(I),K),K=1,%(ndir)d),I=1,NTENS), &
      ((GETIM(STATEV(I),K),K=1,%(ndir)d),I=1,MAX(NSTATV,1))
    S_CARRY=STRESS; X_CARRY=STATEV; SSE_C=SSE; SPD_C=SPD; SCD_C=SCD
    STRAN_IN=STRAN_IN+DSTRANH(:,INC)
    TIME_IN=TIME_IN+DTH(INC)
  END DO
  CLOSE(UO)
END PROGRAM cf_oti_driver
"""


# ---------------------------------------------------------------------------
# configuration files
# ---------------------------------------------------------------------------

def _row(values) -> str:
    return " ".join(repr(float(v)) for v in values)


@dataclass
class RunConfig:
    ntens: int
    nstatv: int
    nprops: int
    ndi: int
    nshr: int
    props: list
    statev0: list
    cmname: str
    increments: list           # [(dstran, f0, f1, drot, dtime, temp, dtemp)]
    coords: tuple = (0.0, 0.0, 0.0)
    call_sdvini: bool = False

    def write(self, directory: Path) -> Path:
        path = Path(directory) / CONFIG_FILE
        lines = [f"{self.ntens} {self.nstatv} {self.nprops} {self.ndi} {self.nshr} "
                 f"{len(self.increments)} {1 if self.call_sdvini else 0}",
                 (self.cmname or "MATERIAL")[:80],
                 _row(self.props if self.props else [0.0]),
                 _row(self.statev0 if self.statev0 else [0.0] * max(self.nstatv, 1)),
                 _row(self.coords)]
        for dstran, f0, f1, drot, dtime, temp, dtemp in self.increments:
            lines.append(_row([dtime, temp, dtemp]))
            lines.append(_row(dstran))
            lines.append(_row(np.asarray(f0).reshape(-1)))
            lines.append(_row(np.asarray(f1).reshape(-1)))
            lines.append(_row(np.asarray(drot).reshape(-1)))
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return path


@dataclass
class Perturbation:
    mode: str                  # "local" | "total"
    kind: str                  # props|statev|dstran|dfgrd1|stress
    index: int                 # 1-based (0 for dfgrd1)
    step: float                # absolute
    direction: tuple = ((0, 0, 0), (0, 0, 0), (0, 0, 0))   # strain direction for dfgrd1


def write_perturbations(directory: Path, perturbations: Sequence[Perturbation]) -> Path:
    path = Path(directory) / PERT_FILE
    lines = [str(len(perturbations))]
    for p in perturbations:
        lines.append(f"{1 if p.mode == 'local' else 2} {KIND[p.kind]} {int(p.index)} "
                     f"{float(p.step)!r} " + _row(np.asarray(p.direction, float).reshape(-1)))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


@dataclass
class Seed:
    kind: str
    index: int
    direction: int             # 1-based OTI imaginary direction
    strain: tuple = ((0, 0, 0), (0, 0, 0), (0, 0, 0))


def write_seeds(directory: Path, mode: str, seeds: Sequence[Seed]) -> Path:
    path = Path(directory) / SEED_FILE
    lines = [f"{1 if mode == 'local' else 2} {len(seeds)}"]
    for s in seeds:
        lines.append(f"{KIND[s.kind]} {int(s.index)} {int(s.direction)} "
                     + _row(np.asarray(s.strain, float).reshape(-1)))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# output parsing
# ---------------------------------------------------------------------------

@dataclass
class RealOutput:
    initial_statev: np.ndarray
    base: dict = field(default_factory=dict)      # inc -> dict(stress, statev, ddsdde, sse, spd, scd, pnewdt)
    local: dict = field(default_factory=dict)     # (inc, ip, sign) -> (stress, statev, pnewdt)
    total: dict = field(default_factory=dict)     # (ip, sign, inc) -> (stress, statev, pnewdt)
    #: hidden-state gate records, all fields like ``base``:
    replay: dict = field(default_factory=dict)        # inc -> unperturbed call after the local block
    total_replay: dict = field(default_factory=dict)  # ip -> increment-1 call after total block ip
    zero_total: dict = field(default_factory=dict)    # inc -> h=0 total re-run at the end
    #: quad driver only: perturbed minus base output, differenced in REAL(16)
    #: and rounded once -- full relative precision of the difference itself
    local_delta: dict = field(default_factory=dict)   # (inc, ip, sign) -> (dstress, dstatev)
    total_delta: dict = field(default_factory=dict)   # (ip, sign, inc) -> (dstress, dstatev)


def _floats(tokens):
    out = []
    for t in tokens:
        try:
            out.append(float(t))
        except ValueError:            # Fortran writes e.g. 1.0-310 without the E
            m = re.match(r"^([-+]?\d*\.?\d+)([-+]\d+)$", t)
            out.append(float(f"{m.group(1)}e{m.group(2)}") if m else float("nan"))
    return np.array(out)


def parse_real_output(path: Path, ntens: int, nstatv: int) -> RealOutput:
    nx = max(nstatv, 1)
    result = RealOutput(initial_statev=np.zeros(nx))
    for line in Path(path).read_text().splitlines():
        parts = line.split()
        if not parts:
            continue
        tag = parts[0]
        if tag == "I":
            result.initial_statev = _floats(parts[1:1 + nx])
        elif tag in ("B", "R", "Q", "Z"):
            inc = int(parts[1])
            v = _floats(parts[2:])
            o = 0
            stress = v[o:o + ntens]; o += ntens
            statev = v[o:o + nx]; o += nx
            ddsdde = v[o:o + ntens * ntens].reshape(ntens, ntens); o += ntens * ntens
            sse, spd, scd, pnewdt = v[o:o + 4]
            {"B": result.base, "R": result.replay, "Q": result.total_replay,
             "Z": result.zero_total}[tag][inc] = dict(
                stress=stress, statev=statev[:nstatv], ddsdde=ddsdde,
                sse=sse, spd=spd, scd=scd, pnewdt=pnewdt)
        elif tag in ("L", "T"):
            a, b, c = int(parts[1]), int(parts[2]), int(parts[3])
            v = _floats(parts[4:])
            entry = (v[:ntens], v[ntens:ntens + nx][:nstatv], v[ntens + nx])
            (result.local if tag == "L" else result.total)[(a, b, c)] = entry
        elif tag in ("l", "t"):        # quad driver: (perturbed - base) computed in REAL(16)
            a, b, c = int(parts[1]), int(parts[2]), int(parts[3])
            v = _floats(parts[4:])
            entry = (v[:ntens], v[ntens:ntens + nx][:nstatv])
            (result.local_delta if tag == "l" else result.total_delta)[(a, b, c)] = entry
    return result


@dataclass
class OtiOutput:
    base: dict = field(default_factory=dict)      # inc -> dict(stress, statev, ddsdde, ...)
    dstress: dict = field(default_factory=dict)   # inc -> (ntens, ndir)
    dstatev: dict = field(default_factory=dict)   # inc -> (nstatv, ndir)


def parse_oti_output(path: Path, ntens: int, nstatv: int, ndir: int) -> OtiOutput:
    nx = max(nstatv, 1)
    result = OtiOutput()
    for line in Path(path).read_text().splitlines():
        parts = line.split()
        if not parts:
            continue
        if parts[0] == "B":
            inc = int(parts[1]); v = _floats(parts[2:]); o = 0
            stress = v[o:o + ntens]; o += ntens
            statev = v[o:o + nx]; o += nx
            ddsdde = v[o:o + ntens * ntens].reshape(ntens, ntens); o += ntens * ntens
            sse, spd, scd, pnewdt = v[o:o + 4]
            result.base[inc] = dict(stress=stress, statev=statev[:nstatv], ddsdde=ddsdde,
                                    sse=sse, spd=spd, scd=scd, pnewdt=pnewdt)
        elif parts[0] == "D":
            inc = int(parts[1]); v = _floats(parts[2:])
            result.dstress[inc] = v[:ntens * ndir].reshape(ntens, ndir)
            result.dstatev[inc] = v[ntens * ndir:ntens * ndir + nx * ndir].reshape(nx, ndir)[:nstatv]
    return result


# ---------------------------------------------------------------------------
# building
# ---------------------------------------------------------------------------

@dataclass
class Build:
    program: Optional[Path] = None
    ok: bool = False
    reason: str = ""
    log: str = ""
    command: list = field(default_factory=list)

    def as_dict(self) -> dict:
        return {"program": str(self.program) if self.program else None, "ok": self.ok,
                "reason": self.reason, "log_tail": self.log[-1500:],
                "command": [str(c) for c in self.command]}


def _gfortran_form_flags(path: Path, text: str) -> list:
    from umat_oti.fortran.normalize import detect_source_form
    form = detect_source_form(path, text)
    if str(form).lower().startswith("free"):
        return ["-ffree-form", "-ffree-line-length-none"]
    return ["-ffixed-form", "-ffixed-line-length-none"]


def prepare_original_source(source: Path, work: Path) -> tuple:
    """Copy of the original with console writes silenced and the author's
    PROGRAM removed (both done by the corpus replay helpers, unchanged).
    Returns (prepared_path, text, form_flags)."""
    from umat_oti.abaqus.probe import silence_console_writes
    from umat_oti.abaqus.replay import _text_of, without_the_authors_program
    from umat_oti.fortran.normalize import detect_source_form

    text = _text_of(Path(source))
    form = detect_source_form(Path(source), text)
    text, _ = silence_console_writes(text, form)
    text, _ = without_the_authors_program(text, form)
    suffix = Path(source).suffix if Path(source).suffix.lower() in (".f", ".for", ".f90", ".f77") else ".f"
    prepared = Path(work) / f"original_umat{suffix}"
    prepared.write_text(text, encoding="utf-8")
    return prepared, text, _gfortran_form_flags(Path(source), text)


def stub_block(source_text: str) -> str:
    from umat_oti.abaqus.replay import _replay_utility_stubs
    from umat_oti.abaqus.single_call import drop_stubs_defined_by
    from umat_oti.validation.actual_umat_higher_order_generic import _abaqus_utility_stubs
    stubs, _ = drop_stubs_defined_by(_abaqus_utility_stubs() + _replay_utility_stubs(),
                                     source_text)
    return stubs


def build_real(work: Path, units: Sequence[Path], source_text: str, *,
               objects: Sequence[Path] = (), module_dirs: Sequence[Path] = (),
               sdvini: bool = False, unit_flags: Sequence[Sequence[str]] = (),
               compiler: str = "gfortran", opt: str = "-O0",
               extra_flags: Sequence[str] = (), quad: bool = False) -> Build:
    """Compile ``units`` (each with its own form flags) + the real driver.

    ``extra_flags`` go on every unit (the hidden-state gate's variants:
    ``-finit-real=snan ...`` / ``-finit-real=zero ...`` / ``-fcheck=bounds``).
    """
    from umat_oti.abaqus.single_call import install_headers
    work = Path(work)
    work.mkdir(parents=True, exist_ok=True)
    if shutil.which(compiler) is None:
        return Build(reason=f"{compiler} not on PATH")
    install_headers(work)
    if quad:
        # the header's documented content, promoted with the source
        for name in ("aba_param.inc", "ABA_PARAM.INC", "aba_param.INC", "ABA_PARAM.inc"):
            (work / name).write_text("      implicit real*16(a-h,o-z)\n"
                                     "      parameter (nprecd=2)\n", encoding="utf-8")
    elif not any((work / n).is_file() for n in ("aba_param.inc", "ABA_PARAM.INC")):
        # No Abaqus installation: the header's documented content.
        for name in ("aba_param.inc", "ABA_PARAM.INC", "aba_param.INC", "ABA_PARAM.inc"):
            (work / name).write_text("      implicit real*8(a-h,o-z)\n"
                                     "      parameter (nprecd=2)\n", encoding="utf-8")
    driver = work / "cf_real_driver.f90"
    template = quad_driver("", sdvini) if quad else REAL_DRIVER
    stubs = stub_block(source_text)
    driver.write_text(template % {
        "common": _COMMON_DECL, "read": _READ_CONFIG % {"config": CONFIG_FILE},
        "pert": PERT_FILE, "out": REAL_OUT, "sdvini": _SDVINI if sdvini else "    CONTINUE",
        "stubs": quadify(stubs) if quad else stubs}, encoding="utf-8")
    includes = [f"-I{work}"] + [f"-I{d}" for d in module_dirs]
    objs = []
    log = ""
    for k, unit in enumerate(units):
        flags = list(unit_flags[k]) if k < len(unit_flags) else []
        obj = work / f"cf_unit_{k}.o"
        cmd = [compiler, opt, "-std=legacy", *flags, *extra_flags, *includes, "-c", str(unit),
               "-o", str(obj), f"-J{work}"]
        done = subprocess.run(cmd, cwd=work, capture_output=True, text=True)
        log += done.stdout + done.stderr
        if done.returncode != 0:
            return Build(reason=f"compile of {Path(unit).name} failed (exit {done.returncode})",
                         log=log, command=cmd)
        objs.append(obj)
    program = work / "cf_real_driver"
    cmd = [compiler, opt, "-ffree-line-length-none", *includes, str(driver), *map(str, objs),
           *map(str, objects), "-o", str(program)]
    done = subprocess.run(cmd, cwd=work, capture_output=True, text=True)
    log += done.stdout + done.stderr
    if done.returncode != 0 or not program.is_file():
        return Build(reason=f"driver link failed (exit {done.returncode})", log=log, command=cmd)
    return Build(program=program, ok=True, log=log, command=cmd)


def run_program(build: Build, work: Path, timeout: int = 1800) -> tuple:
    if not build.ok:
        return False, build.reason
    try:
        done = subprocess.run([str(build.program)], cwd=str(work), capture_output=True,
                              text=True, timeout=timeout, stdin=subprocess.DEVNULL)
    except (OSError, subprocess.SubprocessError) as error:
        return False, f"{type(error).__name__}: {error}"
    if done.returncode != 0:
        return False, f"exit {done.returncode}: {(done.stdout + done.stderr)[-1500:]}"
    return True, (done.stdout + done.stderr)[-500:]


def kstep_rank(lifted_source: str) -> int:
    """Rank of the 36th dummy (KSTEP slot) of ``umat_oti`` in a lifted source.

    Some corpus sources declare that slot as ``JSTEP(4)``. A legacy call with
    a scalar works by accident; a module procedure with an explicit interface
    refuses it, so the driver has to pass an array exactly when the routine
    declares one.
    """
    match = re.search(r"subroutine\s+umat_oti\s*\(([^)]*)\)", lifted_source, re.IGNORECASE)
    if not match:
        return 0
    dummies = [d.strip() for d in match.group(1).replace("&", " ").split(",")]
    if len(dummies) < 36:
        return 0
    name = dummies[35]
    body = lifted_source[match.end():]
    end = re.search(r"end\s+subroutine\s+umat_oti", body, re.IGNORECASE)
    body = body[:end.start()] if end else body
    if re.search(rf"(?<![\w%]){re.escape(name)}\s*\(", body, re.IGNORECASE):
        return 1
    return 0


def build_oti(work: Path, lifted_dir: Path, module: str, type_name: str, ndir: int, *,
              compiler: str = "gfortran", kstep_rank: int = 0) -> Build:
    """Compile the run-time-seeded OTI driver against a lifted build's objects."""
    work = Path(work)
    driver = Path(lifted_dir) / "cf_oti_driver.f90"
    source = OTI_DRIVER % {
        "module": module, "type": type_name, "common": _COMMON_DECL,
        "read": _READ_CONFIG % {"config": CONFIG_FILE}, "seeds": SEED_FILE,
        "out": OTI_OUT, "ndir": ndir}
    if kstep_rank:
        source = source.replace("INTEGER :: NOEL,NPT,LAYER,KSPT,KSTEP,KINC",
                                "INTEGER :: NOEL,NPT,LAYER,KSPT,KSTEP(4),KINC")
        source = source.replace("KSTEP=1; KINC=INC", "KSTEP=0; KSTEP(1)=1; KINC=INC")
    driver.write_text(source, encoding="utf-8")
    objs = [Path(lifted_dir) / name for name in (
        "master_parameters.o", "real_utils.o", f"{module}.o", "oti_intrinsics.o",
        "umat_oti_lifted.o", "abaqus_stubs.o")]
    missing = [o.name for o in objs if not o.is_file()]
    if missing:
        return Build(reason=f"lifted build is missing {missing}")
    program = Path(lifted_dir) / "cf_oti_driver"
    cmd = [compiler, "-O1", "-std=legacy", "-ffree-line-length-none", f"-I{lifted_dir}",
           str(driver), *map(str, objs), "-o", str(program)]
    done = subprocess.run(cmd, cwd=lifted_dir, capture_output=True, text=True)
    if done.returncode != 0 or not program.is_file():
        return Build(reason=f"OTI driver link failed (exit {done.returncode})",
                     log=done.stdout + done.stderr, command=cmd)
    return Build(program=program, ok=True, log=done.stdout + done.stderr, command=cmd)
