PROGRAM original_reference_driver
  IMPLICIT NONE
  INTEGER, PARAMETER :: NTENS=6, NSTATV=1, NPROPS=4
  REAL(8) :: STRESS(NTENS),STATEV(NSTATV),DDSDDE(NTENS,NTENS),SSE,SPD,SCD,RPL
  REAL(8) :: DDSDDT(NTENS),DRPLDE(NTENS),DRPLDT,STRAN(NTENS),DSTRAN(NTENS)
  REAL(8) :: TIME(2),DTIME,TEMP,DTEMP,PREDEF(1),DPRED(1),PROPS(NPROPS),COORDS(3)
  REAL(8) :: DROT(3,3),PNEWDT,CELENT,DFGRD0(3,3),DFGRD1(3,3)
  INTEGER :: NDI,NSHR,NOEL,NPT,LAYER,KSPT,KSTEP,KINC,I,NINC
  CHARACTER(80) :: CMNAME
  STRESS=0.0_8;STATEV=0.0_8;DDSDDE=0.0_8;STRAN=0.0_8;DSTRAN=0.0_8
  SSE=0.0_8;SPD=0.0_8;SCD=0.0_8;RPL=0.0_8;DDSDDT=0.0_8;DRPLDE=0.0_8;DRPLDT=0.0_8
  TIME=0.0_8;DTIME=1.0_8;TEMP=293.15_8;DTEMP=0.0_8;PREDEF=0.0_8;DPRED=0.0_8
  COORDS=0.0_8;DROT=0.0_8;DFGRD0=0.0_8;DFGRD1=0.0_8
  DO I=1,3
    DROT(I,I)=1.0_8;DFGRD0(I,I)=1.0_8;DFGRD1(I,I)=1.0_8
  END DO
  PNEWDT=1.0_8;CELENT=1.0_8;CMNAME='ORIGINAL_REFERENCE'
  NDI=3;NSHR=3;NOEL=1;NPT=1;LAYER=1;KSPT=1;KSTEP=1
  READ(*,*) PROPS
  READ(*,*) NINC
  DO KINC=1,NINC
    READ(*,*) DSTRAN
    CALL UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,RPL,DDSDDT,DRPLDE,DRPLDT, &
      STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,NDI,NSHR,NTENS,NSTATV, &
      PROPS,NPROPS,COORDS,DROT,PNEWDT,CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
    WRITE(*,'(7(ES26.17E3,1X))') STRESS,STATEV
    STRAN=STRAN+DSTRAN;TIME=TIME+DTIME
  END DO
END PROGRAM original_reference_driver
SUBROUTINE GETOUTDIR(PATH,NCHAR)
  CHARACTER(*) :: PATH
  INTEGER :: NCHAR
  PATH='.';NCHAR=1
END SUBROUTINE GETOUTDIR
SUBROUTINE XIT
  WRITE(0,'(A)') 'original UMAT called XIT (local solve did not converge)'
  STOP 3
END SUBROUTINE XIT
