!===============================================================
! Generic OTI parameter-sensitivity material-point driver.
! Generated by umat_oti.transform.parameter_sensitivity_transform.
!===============================================================
PROGRAM ps_driver
  USE master_parameters, ONLY: DP
  USE otim4n1
  USE umat_oti_lifted_mod
  IMPLICIT NONE

  INTEGER, PARAMETER :: N_INC     = 20
  INTEGER, PARAMETER :: NTENS_    = 6
  INTEGER, PARAMETER :: NSTATV_   = 1
  INTEGER, PARAMETER :: NPROPS_   = 4
  INTEGER, PARAMETER :: NDI_      = 3
  INTEGER, PARAMETER :: NSHR_     = 3

  TYPE(ONUMM4N1) :: STRESS(NTENS_), STATEV(NSTATV_), PROPS(NPROPS_)
  TYPE(ONUMM4N1) :: DSTRAN(NTENS_), STRAN(NTENS_)
  TYPE(ONUMM4N1) :: DDSDDE(NTENS_,NTENS_)
  TYPE(ONUMM4N1) :: SSE, SPD, SCD, RPL
  TYPE(ONUMM4N1) :: DDSDDT(NTENS_), DRPLDE(NTENS_), DRPLDT
  TYPE(ONUMM4N1) :: PNEWDT, CELENT
  TYPE(ONUMM4N1) :: DFGRD0(3,3), DFGRD1(3,3)
  TYPE(ONUMM4N1) :: TIME(2), DTIME, TEMP, DTEMP, PREDEF(1), DPRED(1)
  TYPE(ONUMM4N1) :: DFGRDINC(3,3)
  TYPE(ONUMM4N1) :: COORDS(3), DROT(3,3)
  CHARACTER(len=80) :: CMNAME
  INTEGER :: NOEL, NPT, LAYER, KSPT, KSTEP, KINC
  INTEGER :: I, K, INC
  INTEGER :: U_PRIMAL, U_SIGMA, U_STATE

  ! -- Seed PROPS with OTI directions --------------------------
  PROPS(1) = 2.10000000000000000e+05_DP + E1
  PROPS(2) = 2.99999999999999989e-01_DP + E2
  PROPS(3) = 2.50000000000000000e+02_DP + E3
  PROPS(4) = 2.00000000000000000e+03_DP + E4

  ! -- Initialise state -----------------------------------------
  DO I = 1, NTENS_
     STRESS(I) = 0.0_DP
     STRAN(I)  = 0.0_DP
     DSTRAN(I) = 0.0_DP
  END DO
  DO I = 1, NSTATV_
     STATEV(I) = 0.0_DP
  END DO

  DDSDDE = 0.0_DP
  DDSDDT = 0.0_DP; DRPLDE = 0.0_DP; DRPLDT = 0.0_DP
  SSE = 0.0_DP; SPD = 0.0_DP; SCD = 0.0_DP; RPL = 0.0_DP
  TIME = 0.0_DP; DTIME = 1.0_DP
  TEMP = 293.15_DP; DTEMP = 0.0_DP
  PREDEF = 0.0_DP; DPRED = 0.0_DP
  COORDS = 0.0_DP; DROT = 0.0_DP
  DFGRD0 = 0.0_DP; DFGRD1 = 0.0_DP
  DO I = 1, 3
     DROT(I,I) = 1.0_DP
     DFGRD0(I,I) = 1.0_DP
     DFGRD1(I,I) = 1.0_DP
  END DO
  DFGRDINC = 0.0_DP
  PNEWDT = 1.0_DP; CELENT = 1.0_DP
  CMNAME = "MATERIAL_OTI"
  NOEL = 1; NPT = 1; LAYER = 1; KSPT = 1; KSTEP = 1; KINC = 1

  ! -- CSV headers ----------------------------------------------
  OPEN(NEWUNIT=U_PRIMAL, FILE="primal_stress_state_OTI.csv", STATUS="REPLACE", ACTION="WRITE")
  WRITE(U_PRIMAL, '(A)') "increment,method,stress_1,stress_2,stress_3,stress_4,stress_5,stress_6,EQPLAS"
  OPEN(NEWUNIT=U_SIGMA, FILE="DSIGMA_DP_OTI.csv", STATUS="REPLACE", ACTION="WRITE")
  WRITE(U_SIGMA, '(A)') "increment,stress_component,method,E,NU,SIGY0,H"
  OPEN(NEWUNIT=U_STATE, FILE="DSTATEV_DP_OTI.csv", STATUS="REPLACE", ACTION="WRITE")
  WRITE(U_STATE, '(A)') "increment,state_variable,method,E,NU,SIGY0,H"

  ! -- Loading loop ---------------------------------------------
  DO INC = 1, N_INC
     KINC = INC
     DSTRAN(1) = 1.00000000000000005e-04_DP
     DSTRAN(2) = 0.00000000000000000e+00_DP
     DSTRAN(3) = 0.00000000000000000e+00_DP
     DSTRAN(4) = 0.00000000000000000e+00_DP
     DSTRAN(5) = 0.00000000000000000e+00_DP
     DSTRAN(6) = 0.00000000000000000e+00_DP

     CALL umat_oti(STRESS, STATEV, DDSDDE, SSE, SPD, SCD, &
                   RPL, DDSDDT, DRPLDE, DRPLDT, &
                   STRAN, DSTRAN, TIME, DTIME, TEMP, DTEMP, &
                   PREDEF, DPRED, CMNAME, &
                   NDI_, NSHR_, NTENS_, NSTATV_, PROPS, NPROPS_, &
                   COORDS, DROT, PNEWDT, CELENT, DFGRD0, DFGRD1, &
                   NOEL, NPT, LAYER, KSPT, KSTEP, KINC)

     WRITE(U_PRIMAL, '(I0,",oti",7(",",ES24.15E3))') INC, STRESS(1)%R, STRESS(2)%R, STRESS(3)%R, STRESS(4)%R, STRESS(5)%R, STRESS(6)%R, STATEV(1)%R
     DO I = 1, NTENS_
        WRITE(U_SIGMA, '(I0,",",I0,",oti",4(",",ES24.15E3))') INC, I, GETIM(STRESS(I), 1), GETIM(STRESS(I), 2), GETIM(STRESS(I), 3), GETIM(STRESS(I), 4)
     END DO
     DO I = 1, NSTATV_
        WRITE(U_STATE, '(I0,",",I0,",oti",4(",",ES24.15E3))') INC, I, GETIM(STATEV(I), 1), GETIM(STATEV(I), 2), GETIM(STATEV(I), 3), GETIM(STATEV(I), 4)
     END DO

     DO I = 1, NTENS_
        STRAN(I) = STRAN(I) + DSTRAN(I)
     END DO
     TIME(1) = TIME(1) + DTIME
     TIME(2) = TIME(2) + DTIME
  END DO

  CLOSE(U_PRIMAL); CLOSE(U_SIGMA); CLOSE(U_STATE)
END PROGRAM ps_driver
