!===============================================================
! OTI-lifted UMAT + helper closure.
! Generated by umat_oti.transform.parameter_sensitivity_transform.
!===============================================================
MODULE umat_oti_lifted_mod
  USE master_parameters, ONLY: DP
  USE otim4n1
  USE oti_intrinsics
  IMPLICIT NONE
  PUBLIC
CONTAINS

subroutine umat_oti(stress, statev, ddsdde, sse, spd, scd, rpl, ddsddt, drplde, drpldt, stran, dstran, time, dtime, temp, dtemp, predef, dpred, cmname, ndi, nshr, ntens, nstatv, props, nprops, coords, drot, pnewdt, celent, dfgrd0, dfgrd1, noel, npt, layer, kspt, kstep, kinc)
    use otim4n1, OTI_HELPER_DP => DP
    implicit type(ONUMM4N1) (a-h,o-z)
    implicit integer (i-n)
    CHARACTER*80 CMNAME
    type(ONUMM4N1) :: STRESS(NTENS), STATEV(NSTATV), DDSDDE(NTENS,NTENS), DDSDDT(NTENS), DRPLDE(NTENS), STRAN(NTENS), DSTRAN(NTENS), TIME(2), PREDEF(1), DPRED(1), PROPS(NPROPS), COORDS(3), DROT(3,3), DFGRD0(3,3), DFGRD1(3,3)
    type(ONUMM4N1) :: FLOW(6)
    real(8), parameter :: ZERO = 0.D0
    real(8), parameter :: ONE = 1.D0
    real(8), parameter :: TWO = 2.D0
    real(8), parameter :: THREE = 3.D0
    real(8), parameter :: SIX = 6.D0
    EMOD=PROPS(1)
    ENU=PROPS(2)
    SIGY0=PROPS(3)
    HARD=PROPS(4)
    EBULK3=EMOD/(ONE-TWO*ENU)
    EG2=EMOD/(ONE+ENU)
    EG=EG2/TWO
    EG3=THREE*EG
    ELAM=(EBULK3-EG2)/THREE
    DO K1=1,NTENS
    DO K2=1,NTENS
    DDSDDE(K2,K1)=ZERO
    END DO
    END DO
    DO K1=1,NDI
    DO K2=1,NDI
    DDSDDE(K2,K1)=ELAM
    END DO
    DDSDDE(K1,K1)=EG2+ELAM
    END DO
    DO K1=NDI+1,NTENS
    DDSDDE(K1,K1)=EG
    END DO
    DO K1=1,NTENS
    DO K2=1,NTENS
    STRESS(K2)=STRESS(K2)+DDSDDE(K2,K1)*DSTRAN(K1)
    END DO
    END DO
    EQPLAS=STATEV(1)
    SMISES=(STRESS(1)-STRESS(2))**2.0D0+(STRESS(2)-STRESS(3))**2.0D0 +(STRESS(3)-STRESS(1))**2.0D0
    DO K1=NDI+1,NTENS
    SMISES=SMISES+SIX*STRESS(K1)**2.0D0
    END DO
    SMISES=SQRT(SMISES/TWO)
    SYIEL0=SIGY0+HARD*EQPLAS
    IF (REAL(SMISES).GT.REAL(SYIEL0)) THEN
    SHYDRO=(STRESS(1)+STRESS(2)+STRESS(3))/THREE
    DO K1=1,NDI
    FLOW(K1)=(STRESS(K1)-SHYDRO)/SMISES
    END DO
    DO K1=NDI+1,NTENS
    FLOW(K1)=STRESS(K1)/SMISES
    END DO
    DEQPL=(SMISES-SYIEL0)/(EG3+HARD)
    SYIELD=SYIEL0+HARD*DEQPL
    DO K1=1,NDI
    STRESS(K1)=FLOW(K1)*SYIELD+SHYDRO
    END DO
    DO K1=NDI+1,NTENS
    STRESS(K1)=FLOW(K1)*SYIELD
    END DO
    EQPLAS=EQPLAS+DEQPL
    EFFG=EG*SYIELD/SMISES
    EFFG2=TWO*EFFG
    EFFG3=THREE/TWO*EFFG2
    EFFLAM=(EBULK3-EFFG2)/THREE
    EFFHRD=EG3*HARD/(EG3+HARD)-EFFG3
    DO K1=1,NTENS
    DO K2=1,NTENS
    DDSDDE(K2,K1)=ZERO
    END DO
    END DO
    DO K1=1,NDI
    DO K2=1,NDI
    DDSDDE(K2,K1)=EFFLAM
    END DO
    DDSDDE(K1,K1)=EFFG2+EFFLAM
    END DO
    DO K1=NDI+1,NTENS
    DDSDDE(K1,K1)=EFFG
    END DO
    DO K1=1,NTENS
    DO K2=1,NTENS
    DDSDDE(K2,K1)=DDSDDE(K2,K1)+EFFHRD*FLOW(K2)*FLOW(K1)
    END DO
    END DO
    END IF
    STATEV(1)=EQPLAS
    RETURN
end subroutine umat_oti

END MODULE umat_oti_lifted_mod
